### ISSUE TITLE
Missing media when adding audio/video tracks quickly while connected to room

### ISSUE THREAD

**Issue by ptankTwilio** [twilio/video-quickstart-swift#101]
While connected to a Room there is a bug in our negotiation of media when adding audio and/or video tracks quickly. In some cases video is not flowing to participants.

Steps to Reproduce
1 . Alice connect to Room B with no media
2. Bob connect to Room B with no media
3. Bob adds two `TVILocalVideoTrack` s with `TVIScreenCapturer` and `TVICameraCapturer` one right after the other.

Expected Result
Both video tracks are visible to Alice.

Actual Result
Both video tracks are received but only the `TVICameraCapturer` video track is visible to Alice

Workaround
Insert 2-5 second delay between successive additions of audio and video tracks.

**Comment by ceaglest** [comment]
We tried to solve this issue in a similar way to our JavaScript SDK, but the fix didn't land in time for our upcoming `1.0.0` release. We plan to promptly address this issue in our next 1.0.1 update. cc @ramapal.

**Comment by paynerc** [comment]
`1.0.1` has *just* been released.
