### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by treyrich** [twilio/video-quickstart-swift#103]
Are there plans to support distribution of the framework through Carthage?

**Comment by ceaglest** [comment]
Hi @treyrich,

Yes, we do intend to support Carthage. 

We've had some discussions about this internally and are interested in the idea. Let me circle back with the team and I'll update the issue with more info.

Thanks,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @treyrich,

Our Authy team has recently started supporting Carthage for their [iOS SDK](https://media.twiliocdn.com/sdk/ios/auth/releases/TwilioAuth.json). We will also be taking steps to integrate Carthage into our Video SDK release process. This work is scheduled to start after our P2P Rooms GA release at the end of the month.

More updates to come.

Best,
Chris

**Comment by admeister** [comment]
+1

**Comment by ceaglest** [comment]
Thanks for the feedback. I don't have any new progress to report, but we do still intend to offer Carthage support. I will circle back with the team on this one during our next planning meeting.

**Comment by paynerc** [comment]
Just a quick update on this. We have an issue in this sprint to add Carthage support. It should be available in the somewhat near future. I will update this ticket when it is available.

**Comment by paynerc** [comment]
Good news everybody! We have added Carthage support for Twilio Video iOS. At the present time the latest 1.x and 2.x releases are available. As new releases are made, they will also be added.

Please see the [twilio-video-ios](http://github.com/twilio/twilio-video-ios) repository for further information. 

Thank you for your patience while we tackled this.

**Comment by treyrich** [comment]
@paynerc how far behind should we expect the [twilio-video-ios](https://github.com/twilio/twilio-video-ios) repo to be? The changelog [here](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x) says that beta1 was released almost a week ago, but the carthage repo still not gotten the newer release.

**Comment by ceaglest** [comment]
@treyrich is [2.0.0-beta1](https://github.com/twilio/twilio-video-ios/releases/tag/v2.0.0-beta1) not working for you?

**Comment by treyrich** [comment]
@ceaglest totally my bad for not checking the list more thoroughly [here](https://github.com/twilio/twilio-video-ios/releases) I had assumed that they'd show up in descending order like most repos, but beta1 is below the previous 2 previews.

**Comment by ceaglest** [comment]
No problem. Releasing artifacts to twilio-video-ios is something we do for every version. We will have a look, but it's possible that the `preview` vs `beta` pre-release qualifiers are messing the ordering up on the releases page.
