### ISSUE TITLE
Continuous disconnect after minute or 1 minute and 15 sec

### ISSUE THREAD

**Issue by pryaniq** [twilio/video-quickstart-swift#105]
Disconnect occurs in every video-call session after 01:00 - 01:15 time.
`– room:didDisconnectWithError:` is not called before disconnect..
Logs will be added in attachments.

[twilio-video_call_disconect_outgoing.txt](https://github.com/twilio/video-quickstart-swift/files/905867/twilio-video_call_disconect_outgoing.txt)
[twilio-video_call_disconect_incoming.txt](https://github.com/twilio/video-quickstart-swift/files/905868/twilio-video_call_disconect_incoming.txt)

**Comment by ceaglest** [comment]
Hi @pryaniq,

I'm sorry to hear that you are experiencing this issue. I was able to gather the server side logs for the Room, and will begin investigating from there.

Could you provide un-abridged versions of the two logs you attached? That would help me chase down the client side more easily.

Thanks,
Chris Eagleston

**Comment by pryaniq** [comment]
Hi @ceaglest 

Thank you for answer.

I'm attaching full logs:
[twilio-video_call_disconect_outgoing.txt](https://github.com/twilio/video-quickstart-swift/files/909753/twilio-video_call_disconect_outgoing.txt)
[twilio-video_call_disconect_incoming.txt](https://github.com/twilio/video-quickstart-swift/files/909754/twilio-video_call_disconect_incoming.txt)


Also, I'd like notice that I'm using `TwilioVideo` and `TwilioVoiceClient` at the same time.

**Comment by ceaglest** [comment]
Hi @pryaniq,

Thank you! I'm looking into this today and will get back to you with more info.

Chris

**Comment by ceaglest** [comment]
Hi @pryaniq,

Sorry for not following up on this issue. I'm currently working through our GA release and will get back to you once it goes live.

Best,
Chris

**Comment by ptankTwilio** [comment]
@pryaniq Sorry for the delay. We have fixed many signaling issues in last few months, I think the problem you were observing might have got fixed in the latest version of Video SDK. We have released TwilioVideo 1.2.1 yesterday. I  encourage you to use 1.2.1 and let us know if you are still observing the problem. 

Change logs - https://www.twilio.com/docs/api/video/changelogs/ios#121-july-11-2017

**Comment by pryaniq** [comment]
Hi @ptankTwilio

Thank you!

Right now we don't support project with using TwilioVideo SDK. But if we return to development, I definitely report about problem. 👍

**Comment by ptankTwilio** [comment]
@pryaniq Thanks for the update. Our TwilioVideo 1.2.1 is stable and has many new features in it. We would love to know how you find it and hear feedbacks from you when you try it out. I am closing the ticket as it is very old but feel free to file a new one if you run through any issue while using the video SDK.
