### ISSUE TITLE
Close AVAudioSession?

### ISSUE THREAD

**Issue by patreu22** [twilio/video-quickstart-swift#107]
Hey, 
With Twilio Video I created video chat.
Everytime I lock the iPhone and unlock then I get the following error and everything crashes:

```
VAudioSession.mm:1053:-[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
```

How do I deactivate this Audio session?
I'm not even sure which object is responsible for that?

Thanks for your help!

**Comment by ptankTwilio** [comment]
@patreu22  Can you provide more details on your used case? Are you explicitly deactivating AudioSession in your application code?  Please note that video SDK take care of activating and deactivating audio session when it is in a video call.

**Comment by patreu22** [comment]
Hello @ptankTwilio 
The use-case is quite simple: After a button tap the iPhone user connects through Twilio to an authority. I'm using the TwilioVideo library. When the user locks the phone or closes the app to the background the call should be canceled. I handle that by having a `.UIApplicationDidEnterBackground`Listener.
That works finde for just closing the app.
If the App gets locked  the `.UIApplicationDidEnterBackground`Notification is triggered and the call is shut down. If I reopen the app for a second everything looks fine, but then the app freezes and crashes. Output to the console is the text I posted above. 
I also have a `(lldb) ` and a `SIGPIPE` 

<img width="778" alt="bildschirmfoto 2017-04-11 um 20 02 37" src="https://cloud.githubusercontent.com/assets/11362357/24923448/dc34d174-1ef1-11e7-9ffe-a123ffa77aae.png">


The crash doesn't happen all the time but in 7/10 I would say. 
I'm working with TVILocalMedia,TVICameraCapturer, TVILocalVideoTrack, TVILocalAudioTrack and TVIParticipant.

**Comment by ptankTwilio** [comment]
@patreu22 Sorry for the delay in responding back. Thanks for providing the details about the used case. We have released TwilioVideo version 1.2.1 yesterday which is more stable. I encourage you to try version 1.2.1 and let me know if you are still able to reproduce the problem.

**Comment by ceaglest** [comment]
Closing this ticket due to lack of activity. Please re-open if you still need help with AVAudioSession control, or are experiencing crashes.

**Comment by vemobileios** [comment]
Hello,

I am also experiencing this error sometimes, after answering the call and connecting to the room. I don't know why.

**Comment by andschdk** [comment]
Hi @piyushtank 
> Please note that video SDK take care of activating and deactivating audio session when it is in a video call.

How are you deactivating the audio session. If one need other sources to reactivate after a call e.g. music app, what necessary steps should be taken? I guess you are not using the `AVAudioSession.SetActiveOptions.notifyOthersOnDeactivation` option when deactivating?

Do I need to use the `TVIDefaultAudioDevice`to solve this?
