### ISSUE TITLE
StartCallAction transaction request failed: The operation couldn’t be completed

### ISSUE THREAD

**Issue by ambrishverma** [twilio/video-quickstart-swift#122]
I am using the Video SDK and I am using pretty much the same code from VideoCallQuickStart sample. I am constantly getting this error when trying to start the call:

StartCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 1.)

the error description does not help much in understanding what I am doing wrong here. Any help will be really appreciated. Here is the code snippet:

       let callHandle = CXHandle(type: .generic, value: roomName ?? "")
        let startCallAction = CXStartCallAction(call: uuid, handle: callHandle)
        
        startCallAction.isVideo = true
        let transaction = CXTransaction(action: startCallAction)
        
        callKitCallController.request(transaction)  { error in
            if let error = error {
                NSLog("StartCallAction transaction request failed: \(error.localizedDescription)")
                return
            }
            NSLog("StartCallAction transaction request successful")
        }

**Comment by ambrishverma** [comment]
Needed to enable capabilities for "Voice over IP" in project settings.

**Comment by paramvirgill** [comment]
Twilio Project settings?
