### ISSUE TITLE
Ability to mute remote TVIAudioTrack

### ISSUE THREAD

**Issue by antross** [twilio/video-quickstart-swift#125]
Perhaps I missed this, but I don't see a way to mute a *remote* audio track. 

In the iOS SDK the `isEnabled` property of the `TVIAudioTrack` is read-only and I don't see any other relevant method/object in the documentation (`AudioTrack` in the Android SDK is similarly limited). In the JavaScript SDK I can accomplish this by muting the corresponding `<audio>` element directly. 

I'd like to use this functionality in conference calls where one participant is generating too much noise or is otherwise distracting. The goal is to silence the offending participant while still being able to hear everyone else in the room.

**Comment by ceaglest** [comment]
Hey @antross,

You are correct, we don't currently support muting remote audio tracks in our mobile SDKs. We've received this feature request from individual customers, but not yet on Github. I'll leave this ticket open, and update it as we make progress towards this API improvement.

Thanks,
Chris

**Comment by ceaglest** [comment]
Hi,

We launched our [Group Rooms beta](https://www.twilio.com/blog/2017/05/announcing-programmable-video-group-rooms.html) last week. While this service is fully compatible with our current Clients, we will be making some API enhancements in order to support Track level SIDs in an upcoming minor version release. At the same time we are considering adding the ability to mute remote tracks from the local Client on mobile.

I don't have a firm date for this release yet, but I expect it will land sometime next month. I'll continue to update this ticket as we get closer to a release with this feature.

Best,
Chris Eagleston

**Comment by antross** [comment]
Any update on this? 

We have some additional scenarios where we'd like to use Twilio Video in our apps, but these would match users with potential strangers as part of a group chat in a game. We feel muting is essential to keep disruptive players from spoiling the experience for the whole room. Currently we're limiting Twilio Video to friends-only to avoid this issue.

**Comment by ptankTwilio** [comment]
@antross We have `playbackEnabled` feature implemented and tested on the remote audio track in 2.0, however, we are not planning to add it in 1.x release. At present, we are working on adding more features to 2.0 release. The first 2.0's `preview` release will be available in a few weeks. I will keep you posted when it becomes available for you. I am sorry for the delay.

**Comment by ceaglest** [comment]
Hi @antross,

Yes as @ptankTwilio mentioned this feature will be landing in 2.0.0-preview1. At first we thought we would be adding muting in a minor release, but the changes to our object model were breaking so we decided to bundle it with 2.0 instead.

More updates to come.

- Chris

**Comment by ceaglest** [comment]
Hi @antross,

We've just shipped our 2.0.0-preivew1 release this morning, which adds the ability to mute remote audio tracks. We've added a new `TVIAudioTrack` subclass called `TVIRemoteAudioTrack`, which has a `playbackEnabled` property. Curiously this entry is missing in our [docs](https://media.twiliocdn.com/sdk/ios/video/releases/2.0.0-preview1/docs/Classes/TVIRemoteAudioTrack.html#//api/name/init), but I will make sure that it gets picked up properly there.

https://www.twilio.com/docs/api/video/changelogs/ios

You can see our update sample code (which does not yet use the property) [here](https://github.com/twilio/video-quickstart-swift/tree/2.0.0-preview).

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
We've now released 2.0.0-preview2 which has a minor bug fix and improves docs generation. The API I was referring to can now be found [here](https://media.twiliocdn.com/sdk/ios/video/releases/2.0.0-preview2/docs/Classes/TVIRemoteAudioTrack.html#//api/name/playbackEnabled).

Usage example:

```
    func subscribed(to audioTrack: TVIRemoteAudioTrack,
                    publication: TVIRemoteAudioTrackPublication,
                    for participant: TVIRemoteParticipant) {
       
        // We don't want to hear this audio right now, mute playback.
        audioTrack.isPlaybackEnabled = false
    }
```

**Comment by antross** [comment]
I just updated and tried this out on both our iOS and Android projects. Worked perfectly. Looking forward to the 2.0 release. Thanks!

**Comment by ceaglest** [comment]
Great to hear! Since we've shipped this feature in a preview release and the functionality is complete, I'm going to go ahead and close this ticket out. 

We still have a few more preview releases in mind before our 2.0 APIs are complete enough to go to beta, but I don't expect any more changes in this area.

**Comment by antross** [comment]
Any ETA on finalizing 2.0? I'm eager to take advantage of this addition. ;)

**Comment by vmluan** [comment]
I know this issue belongs to iOS, but i am facing the same problem on javascript. Does javascript sdk support it?

**Comment by ceaglest** [comment]
Hi,

Sorry for the late response, it's easy to miss closed issues.

> Any ETA on finalizing 2.0? I'm eager to take advantage of this addition. ;)

@antross we plan on entering beta later this year, and reaching General Availability with 2.0 early next year. I don't have an exact schedule to share at the moment, as it will depend on the feedback that we receive during the preview and beta period.

> I know this issue belongs to iOS, but i am facing the same problem on javascript. Does javascript sdk support it?

@vmluan You may want to ask in twilio-video.js [project](https://github.com/twilio/twilio-video.js) however, I believe playing audio requires you to manually call [AudioTrack.attach()](https://media.twiliocdn.com/sdk/js/video/releases/1.6.0/docs/AudioTrack.html). If you don't want to play remote audio then don't attach the Track to a DOM element.

Best,
Chris Eagleston

**Comment by vidhyasri2106** [comment]
How to mute it on click of a button? This thread explains how to mute the audio only when it gets subscribed. How to change it somewhere else?

**Comment by piyushtank** [comment]
@vidhyasri2106 The video SDK does not provide any explicit `administrative` control to disable audio (or video track) of a participant in a Room. You can achieve the used case by implementing your signaling though. For example, if Alice, Bob and Charlie are on call, and if you give Alice the Admin role, you can provide UI control on Alice to mute Bob on a Call. Your underlying signaling can send message to Bob to mute his audio or video track. 

Let me know if you have any questions.

**Comment by vidhyasri2106** [comment]
Thanks for the reply. Can you pls post some code snippet on how to enable/disable the audio? Since **audioTrack.isPlaybackEnabled** will work only inside the delegate method.
I want to mute it outside of it on button tap

**Comment by vidhyasri2106** [comment]
Got it. Thanks

**Comment by grago** [comment]
Hello, i was wondering if Twilio has implemented some form of administrative moderation, like remotely muting participants? Or should i implement my own signaling method, as suggested?

Thanks!
