### ISSUE TITLE
Audio-only call?

### ISSUE THREAD

**Issue by r-a-o** [twilio/video-quickstart-swift#126]
Went through the docs and couldn't make out if an audio-only call (one-on-one) is possible. 
(ie., call with no video channel initialisation)

**Comment by paynerc** [comment]
Hello there! Thanks for reaching out!

You certainly can do an audio-only call with the Twilio Video SDK. To do this, you would just add local audio tracks and no local video tracks. You can take the sample app and remove all the video mechanics and will be able to make an audio only call.

Let us know if you have any further questions.

Ryan
