### ISSUE TITLE
Network handoff from Wifi to Wifi is unreliable

### ISSUE THREAD

**Issue by ceaglest** [twilio/video-quickstart-swift#127]
This is an enhancement we are making to our network handoff capabilities, currently targeted for v1.0.2.

#### Problem Description

A Client Alice connects to a Room from a Wifi network. The connection succeeds and at a later time Alice switches to another network Wifi. Sometimes handoff to the new network fails, and if so a room:didDisconnect callback is raised.

#### Solution

Our iOS reachability code was monitoring general (zero address) network connectivity. This works fine for Wifi/Cellular transitions but falls down in the Wifi to Wifi scenario. We are adding reachability monitoring for the signaling socket pair itself so that we can accurately detect all network changes, and re-establish a new TLS socket quickly.

@ptankTwilio is working on this fix, and will provide updates on this ticket.

**Comment by ptankTwilio** [comment]
This issue is fixed in TwilioVideo 1.1.0
