### ISSUE TITLE
Unable to run quickstart on iphone device

### ISSUE THREAD

**Issue by jannunzi** [twilio/video-quickstart-swift#131]
Hi, I was able to build and run the application on the simulator in XCode, but am unable to run it in my iphone. This is the error I'm getting:

None of your accounts are a member of 'SX5J6BN2KX':  An unexpected error occurred. Xcode cannot find a team matching 'SX5J6BN2KX'.
No profiles for 'com.twilio.VideoCallKitQuickStart' were found:  Xcode couldn't find a provisioning profile matching 'com.twilio.VideoCallKitQuickStart'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

Thanks, Jose

**Comment by ptankTwilio** [comment]
@jannunzi  Can you verify that provisioning profile you are using satisfies the bundle identifier of the quickstart app?

**Comment by ceaglest** [comment]
@jannunzi were you able to get code signing up and running? You will also need to change the team to match your own.

**Comment by jannunzi** [comment]
Sorry, not sure how to "check if the provisioning profile satisfies the bundle identifier"...

Thanks, Jose

**Comment by ptankTwilio** [comment]
@jannunzi You can login to apple developer portal developer.apple.com and see check the bundle identifiers and the provisioning profiles. Also as Chris mentioned in the previous post, make sure you are using the correct team on the Xcode project while building and running the app locally.

Apple documentation on Code signing - https://developer.apple.com/support/code-signing/

Please let me know if you have more questions.

**Comment by ceaglest** [comment]
I'm not sure that we can do anything with team selection, other than possibly selecting `None` by default. Either way you will still need to change the team to get signing to work in your development environment. The best advice I can give on resolving code signing issues is to follow Apple's documentation (see @ptankTwilio's link). Closing this issue since it is not actionable.

**Comment by shooding** [comment]
You need to click on both AVPlayerExample and ObjCVideoQuickstart 
and change signing to your team
