### ISSUE TITLE
Video is not created every time even if this method called setupRemoteVideoView()

### ISSUE THREAD

**Issue by MiteshiOS** [twilio/video-quickstart-swift#133]
![img_1528](https://cloud.githubusercontent.com/assets/17427703/26389253/aada7808-4076-11e7-9808-961bef63a552.PNG)
Hello,
I am facing issues with the call, after connected with room many of times only audio session was created even if method for creating video setupRemoteVideoView() was called.

**Comment by paynerc** [comment]
Hi there! Sorry you're having some issues with the Quickstart app. You mention that you have audio flowing from between the devices but no remote video is showing on either device? Is that correct?

It would be helpful to get the logs from at least one (if not both) of the participants so we can try and see why you are not getting the remote video.

You can enable debug logging by adding `TwilioVideo.setLogLevel(.debug)` to the `ViewController`'s `viewDidLoad` method.

Once we have some more information we can dig in and see what the issue you are experiencing is.

Thanks!

Ryan

**Comment by MiteshiOS** [comment]
Hello Ryan,
I attached the text file which contain logs. Please review it and let me know what is wrong. I also attached the screen shot web.
![screen shot 2017-05-25 at 10 11 56 am](https://cloud.githubusercontent.com/assets/17427703/26437153/f9d14abe-4138-11e7-84a6-033b29ca257b.png)
![screen shot 2017-05-25 at 10 14 26 am](https://cloud.githubusercontent.com/assets/17427703/26437154/f9d19622-4138-11e7-92cb-3544b8071b04.png)

**Comment by paynerc** [comment]
Mitesh,

Looking at the logs everything seems to be going along as I would expect. One thing I didn't see in the log is the message:

    INFO:TwilioVideo:[Core]:All ice gathering compeleted and PeerConnection <identifier> is connected

You mentioned that the Web <=> Android scenario is working properly, but the Web <=> iOS is not. Can you tell me a little bit about the networking configuration of both the Android and iOS devices? Are they on the same WiFi network or are they on a cellular network?

Ryan

**Comment by paynerc** [comment]
We did another round of review on these logs and one thing that we notices it that you are not getting any relay (TURN) candidates. Which leads me back to the question I posed earlier. Can you tell me a little bit about the networks you are using for the iOS and Android devices, along with the web app? It seems that the network that the iOS device is connected to is not allowing you to route media back to the webapp. If you had a TURN candidate then you should definitely have connected.

There is a setting in the Twilio Video console that allows you to enable TURN services: 

<img width="887" alt="screen shot 2017-05-25 at 12 57 51 pm" src="https://cloud.githubusercontent.com/assets/25950/26468393/40de14ca-4164-11e7-9725-5bf0824cec22.png">

Can you verify that you have this setting enabled?

Thanks!

Ryan

**Comment by MiteshiOS** [comment]
Ryan,

We are working on the same network for Web <=> Android and Web <=> iOS. Also we tested the android device on cellular data which is working fine but for Web <=> iOS there is no video view even if channel was created. Can you please let me know why the example is provided by Twilio in iOS is not accurate like android. I means in android there is a quick view of video after channel creation compare to iOS. Also is there any other reason except network for not creation of video view  in iOS ?

**Comment by paynerc** [comment]
Mitesh,

A few more questions for you:

1. What version of the iOS SDK are you using?
2. Are you getting the `TwilioVideo.framework` using CocoaPods?
3. Do you have any local modifications to the Quickstart code other than the token retrieval bit?
4. What sort of iOS device are you using? I know you mentioned that you are running on iOS 10.3.1, but not the specific device.
5. Can you try another test and send me the Room SID from the logs? I would like to do a little bit more digging to compare what I saw from the logs yesterday vs today. To find the room sid, you can search the logs for `"sid":"RM` and include the long identifier that begins with `RM`.
6. Are you on an IPv4 or IPv6 network?

You are definitely seeing something strange here as the iOS quickstarts are indeed very similar to Android and the video should follow on very quickly after connecting to the room. What is even more puzzling is that you are getting audio, but no video. If you are able to establish a media stream for one, there is really no reason why the other shouldn't be established as well.

Thanks, 

Ryan

**Comment by MiteshiOS** [comment]
Ryan,

We found an issues and that is because of different usage of AccessToken on both side. Now everything works fine.Thank you for this much support.
