### ISSUE TITLE
Application is stuck after call of "StartCallAction transaction request successful"

### ISSUE THREAD

**Issue by MiteshiOS** [twilio/video-quickstart-swift#136]
I implemented Twilio VideoCallKitQuickStart in my project. As i review the example it is working well. So in my app i am able to send call request successfully and getting this message **"StartCallAction transaction request successful"** , Most of the time it is working well but sometimes after call of  this method **"StartCallAction transaction request successful"** ,application is going to stuck and no one twilio delegate method will be called. As per example this method will be called **"provider:performStartCallAction:"**. But in my 4-5 attempt of call i am getting success in first attempt or sometimes 2 times after that getting only preview view. Also i am attaching my code file please review it and let me know where i am going wrong. 
[Twilio.pdf](https://github.com/twilio/video-quickstart-swift/files/1051752/Twilio.pdf)

**Comment by ceaglest** [comment]
Hi @MiteshiOS,

I believe you already contacted our support engineers about this issue. In response we updated our sample code to invalidate the CXCallProvider in `deinit`. Based on the pdf you provided your `CallAcceptVC` class does not yet have this fix. Have a look at this [Pull Request](https://github.com/twilio/video-quickstart-swift/pull/130) and apply the same change to your source code. This should fix the issue.

Thanks,
Chris

**Comment by MiteshiOS** [comment]
Hi @ceaglest 

Thank you for reply. Now it's working fine.

**Comment by ceaglest** [comment]
No problem, glad we could help and sorry that we weren't clearer in your original support request.

**Comment by MiteshiOS** [comment]
Hello @ceaglest 

I have an one another question. When i am back from background mode to active mode in app, the preview view is stuck. I know this is not happening in demo app. But in my implementation preview view is stuck if i am back from background mode to active mode.
Also i implemented TVICameraCapturerDelegate in my class and it called once when i start call, but when i back from background mode to active mode, this delegate was not called. Actually this is working fine in your demo code. 
So please let me know how can i identify and what is the possible reason if this below method is not called when getting back from background to active mode.

/ /MARK: TVICameraCapturerDelegate
extension CallAcceptVC : TVICameraCapturerDelegate {
    func cameraCapturer(_ capturer: TVICameraCapturer, didStartWith source: TVICameraCaptureSource) {
        self.previewView?.shouldMirror = (source == .frontCamera)
    }
}

This two method also called when going to background mode
 func cameraCapturer(_ capturer: TVICameraCapturer, didFailWithError error: Error) {
        
        logMessage(messageText: "provider: " + error.localizedDescription)
    }
    // Here when it execute it shows => provider: The operation could not be completed
    func cameraCapturerWasInterrupted(_ capturer: TVICameraCapturer, reason: TVICameraCapturerInterruptionReason) {
 
        logMessage(messageText: "provider: cameraCapturerWasInterrupted")
        print(reason.rawValue)
    }
 // Here when it execute it shows => provider: cameraCapturerWasInterrupted  & getting raw value 1

Also in my implementation when i checked value of this self.previewView?.shouldMirror , then i am getting false.
Please let me know how can i solve this.

Thank you 
Mitesh
