### ISSUE TITLE
TVICameraCapturerDelegate not called when returning from the background.

### ISSUE THREAD

**Issue by MiteshiOS** [twilio/video-quickstart-swift#138]
Hello @ceaglest 

I have an one another question. When i am back from background mode to active mode in app, the preview view is stuck. I know this is not happening in demo app. But in my implementation preview view is stuck if i am back from background mode to active mode.
Also i implemented TVICameraCapturerDelegate in my class and it called once when i start call, but when i back from background mode to active mode, this delegate was not called. Actually this is working fine in your demo code. 
So please let me know how can i identify and what is the possible reason if this below method is not called when getting back from background to active mode.

/ /MARK: TVICameraCapturerDelegate
extension CallAcceptVC : TVICameraCapturerDelegate {
    func cameraCapturer(_ capturer: TVICameraCapturer, didStartWith source: TVICameraCaptureSource) {
        self.previewView?.shouldMirror = (source == .frontCamera)
    }
}

This two method also called when going to background mode
    
     func cameraCapturer(_ capturer: TVICameraCapturer, didFailWithError error: Error) {
        
        logMessage(messageText: "provider: " + error.localizedDescription)
    }
    // Here when it execute it shows => provider: The operation could not be completed
    func cameraCapturerWasInterrupted(_ capturer: TVICameraCapturer, reason: TVICameraCapturerInterruptionReason) {
 
        logMessage(messageText: "provider: cameraCapturerWasInterrupted")
        print(reason.rawValue)
    }
 // Here when it execute it shows => provider: cameraCapturerWasInterrupted  & getting raw value 1

Also if i simulate the call from background in my app and after success of call join and video track creation , now if i am going to background and then again coming back to foreground then preview view is not stuck. I think this is strange and unable to found reason for active mode. 
Also in my implementation when i getting back from background mode to active mode i checked value of this self.previewView?.shouldMirror , then i am getting false.
Please let me know how can i solve this.

Thank you 
Mitesh

**Comment by ceaglest** [comment]
Hi @MiteshiOS,

Could you provide debug level logs which demonstrate the sequence of events? As you said this problem doesn't occur in our sample code, so I wonder if you've somehow got two `TVICameraCapturer` instances at play? It's generally not a good idea to create more than one since each owns an `AVCaptureSession` under the hood and they are liable to interrupt each other.

Best,
Chris

**Comment by MiteshiOS** [comment]
Hi @ceaglest 

Can you please let me know why i am unable to print debug level logs in my code. I just set TwilioVideo.setLogLevel(.debug) in viewdidload() but it is not working. Is there any extra set up i need to do for this. Also i added your framework through cocoa pod and the version i am using is pod 'TwilioVideo', '~> 1.0.0'. Please let me know as soon as possible.

Thank you 
Mitesh

**Comment by MiteshiOS** [comment]
Hello @ceaglest 
You still not respond to my question. Please let me know where i am doing wrong. I purchased your service so it's responsibility of your team to provide suggestion on this. I am waiting from last 4 days but no one replay on this thing.

Thank you
Mitesh

**Comment by ceaglest** [comment]
Hi @MiteshiOS,

My apologies for not responding sooner. I see no reason why logging wouldn't work. Can you reproduce this problem by in the Swift QuickStart? For example try adding.

```
    override func viewDidLoad() {
        super.viewDidLoad()
        TwilioVideo.setLogLevel(TVILogLevel.debug)
```

**Comment by ceaglest** [comment]
Hi @MiteshiOS,

I'm closing out this ticket because I haven't heard back from you with more information. As I mentioned you should definitely be able to get logging working, assuming you are not redirecting the console output in your application (see code snippet). As for TVICameraCapturer, creating multiple instances is not recommended as they are liable to interrupt each other. Only a single AVCaptureSession can run at a time, and they do not play nicely together.

Please re-open if you can provide more info.

Regards,
Chris Eagleston

**Comment by gautam1001** [comment]
Hi @ceaglest 

I am facing the same issue, video freezes when I came from background to forground.
Below are the twilio logs:
2018-07-23 15:31:08.230367+0530 Wivi[1894:1827071] WARN:TwilioVideo:[Signaling]:RESIP::TRANSPORT: Can't find matching transport [ V4 127.0.0.1:0 TLS target domain=unspecified mFlowKey=0 ]
2018-07-23 15:31:08.543077+0530 Wivi[1894:1827071] DEBUG:TwilioVideo:[Core]:
Receiving incoming SIP message from infra
SIP/2.0 200 OK

Via: SIP/2.0/TLS 127.0.0.1;received=203.115.107.154;branch=z9hG4bK-524287-1---5c80b516f99cd7c1;rport=49375

Contact: <sip:172.18.6.210:5060>

To: <sip:orchestrator@mobile-endpoint.twilio.com>;tag=42092176_6772d868_8f8bb696-ff91-4d05-b104-5663f7f29ad8

From: "11c759DEdA82F2AD5ABc77eF85Cd52Ab" <sip:11c759DEdA82F2AD5ABc77eF85Cd52Ab@mobile-endpoint.twilio.com>;tag=c5f9b5a7

Call-ID: obq8GUXIDg3cIprewDFryw..

CSeq: 9 UPDATE

Session-Expires: 120

Server: Twilio

X-Twilio-CallSid: CA3d8b26bdc124d8e3becf0252751247c4

X-Twilio-LegInfo: external

X-Twilio-TlsVerify: true

Content-Length: 0


Also the func "cameraCapturer(_ capturer: TVICameraCapturer, didFailWithError error: Error) " calling two time s.

**Comment by ceaglest** [comment]
@gautam1001,

> Also the func "cameraCapturer(_ capturer: TVICameraCapturer, didFailWithError error: Error) " calling two time s.

Are you creating two instances of `TVICameraCapturer`? What were the two errors that were raised? What about other `TVICameraCapturerDelegate` callbacks during this time?

Best,
Chris

**Comment by gautam1001** [comment]
Are you creating two instances of TVICameraCapturer? 
**No,** only one instance is created.

**Issue Resolved**
The AVCaptureSession created by Twilio Video SDK when I connected to a Room (with video track added), is conflicting with the other one in my app. By adding _self.cameraCapturer?.stopCapture()_
 just before making self.cameraCapturer to nil resolve the problem in my case. 
        self.cameraCapturer?.stopCapture()
        self.cameraCapturer = nil

**Comment by ceaglest** [comment]
Perfect, I'm glad to hear it @gautam1001.
