### ISSUE TITLE
How to capture a camera frame (still bitmap from video) ?

### ISSUE THREAD

**Issue by MBuLoft1** [twilio/video-quickstart-swift#142]
This question is similar to the one that was asked here: https://github.com/twilio/video-quickstart-android/issues/89 ... but for iOS.

**Use case**
While Twilio is capturing the video, we want the ability to take a bitmap frame from the video from time to time, so we can send the bitmap to our image processing engine, which works only on bitmaps.

**Solution Approach using TVIVideoRenderer**
```
extension TwilioCamera : TVIVideoRenderer {
    func renderFrame(_ frame: TVIVideoFrame) {
        // Very simple test to get Image from Video Buffer
        let size = CVImageBufferGetCleanRect(imageBuffer)

        // Fails with error: [CIImage initWithCVPixelBuffer:options:] failed 
        // because its pixel format f420 is not supported.
        // Equates to kCVPixelFormatType_420YpCbCr8PlanarFullRange ('f420')
        // Need a YUL420p to ARGB converter here instead of this...
        let ciImage = CIImage(cvImageBuffer: imageBuffer, options: nil)
        ...
    }
...
}
```
In fact at the point where it does `let ciImage = ...` a converter from YUL420p to AGRB (or RGBA)  is required, as indicated in the documentation of _renderFrame_: 

> Your renderer is required to support frames in the format TVIPixelFormatYUV420PlanarFullRange. You should strongly reference (retain) the TVIVideoFrame before this call returns if you want to render it later. Frames are delivered to your renderer at or near their presentation timestamps.

The solution on the Android thread suggests to use OpenCV to perform that conversion. However, we do not want to bring OpenCV into our app just for the purpose of getting a converter which should basically be just one function.

Here are some more or less related links

- https://stackoverflow.com/questions/25659671/how-to-convert-from-yuv-to-ciimage-for-ios
- https://stackoverflow.com/questions/11267693/fastest-yuv420p-to-rgba-conversion-on-ios-using-the-cpu
- https://stackoverflow.com/questions/14765892/how-to-convert-a-kcvpixelformattype-420ypcbcr8biplanarfullrange-buffer-to-yuv420
- Libyuv: https://github.com/illuspas/libyuv-iOS
- Neon: https://stackoverflow.com/questions/8451149/yuv-to-rgba-on-apple-a4-should-i-use-shaders-or-neon
- Helpers: https://developer.apple.com/documentation/accelerate/vimage_transform

Questions...
- Is the use of _TVIVideoRenderer_ the only means of achieving this in Twilio Video ?
- If so, does Twilio or anyone have a ready-made solution to hook in a YUV420p to ARGB converter so that the app can get a valid _ciImage_ in the above example code ?
- Did anyone do the same, and if so can an easy to integrate ready-made solution be provided ?

**Comment by ceaglest** [comment]
Hi @MBuLoft1,

> While Twilio is capturing the video, we want the ability to take a bitmap frame from the video from time to time, so we can send the bitmap to our image processing engine, which works only on bitmaps.

If I understand your use case correctly, you want to create bitmaps from local video captured by `TVICameraCapturer`. If so, this is doable without writing very much code or performing the conversion yourself. Your TVIVideoRenderer just needs to opt into into receiving NV12 images - this is the planar video format which is widely supported by Apple frameworks. I've created a branch which demonstrates creating `CIImage`s from the contents of `TVICameraCapturer` using `TVIVideoRenderer`.

https://github.com/ceaglest/video-quickstart-swift/tree/issue-142

As for remote video you would unfortunately need to do the conversion from I420 to NV12 (or ARGB) yourself before providing them to CIImage. For more discussion on this topic see: https://github.com/twilio/video-quickstart-swift/issues/123.

Best,
Chris Eagleston

**Comment by MBuLoft1** [comment]
Thank you. Added a note in [#123](https://github.com/twilio/video-quickstart-swift/issues/123) about going from I420 to BGRA.

**Comment by ceaglest** [comment]
Hopefully between this ticket, and #123 you've got the answer that you needed. We will do our best to release some sample code which demonstrates what was discussed in these two tickets.

**Comment by kamleshgk** [comment]
Hi @ceaglest , 
I download this fork and tried running 'VideoQuickStart' on my device.

I get this exception stack trace in debugger and finally a crash with this error.
validateRenderPassDescriptor:842: failed assertion `Texture at depthAttachment has usage (0x01) which doesn't specify MTLTextureUsageRenderTarget (0x04)'

`Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 982, TID: 336020, Thread name: (none), Queue name: com.twilio.cameracapturepipeline.session, QoS: 25
Backtrace:
4   TwilioVideo                         0x00000001010bdb70 +[UIApplication(TVIAdditions) tvi_statusBarOrientation] + 72
5   TwilioVideo                         0x0000000100c411f8 -[TVIUserInterfaceObserver observeWithDelegate:] + 48
6   TwilioVideo                         0x0000000100c3ada0 -[TVICameraCapturePipeline setupCaptureSessionWithConsumer:error:] + 1704
7   TwilioVideo                         0x0000000100c39ac0 __60-[TVICameraCapturePipeline startWithConsumer:configuration:]_block_invoke + 48
8   libdispatch.dylib                   0x0000000104a1e338 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x0000000104a1f730 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000104a26740 _dispatch_lane_serial_drain + 744
11  libdispatch.dylib                   0x0000000104a272e0 _dispatch_lane_invoke + 444
12  libdispatch.dylib                   0x0000000104a326c4 _dispatch_workloop_worker_thread + 1304
13  libsystem_pthread.dylib             0x00000001bd607b74 _pthread_wqthread + 272
14  libsystem_pthread.dylib             0x00000001bd60a740 start_wqthread + 8
2020-05-18 17:49:15.410563+0530 VideoQuickStart[982:336020] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication statusBarOrientation]
PID: 982, TID: 336020, Thread name: (none), Queue name: com.twilio.cameracapturepipeline.session, QoS: 25
Backtrace:
4   TwilioVideo                         0x00000001010bdb70 +[UIApplication(TVIAdditions) tvi_statusBarOrientation] + 72
5   TwilioVideo                         0x0000000100c411f8 -[TVIUserInterfaceObserver observeWithDelegate:] + 48
6   TwilioVideo                         0x0000000100c3ada0 -[TVICameraCapturePipeline setupCaptureSessionWithConsumer:error:] + 1704
7   TwilioVideo                         0x0000000100c39ac0 __60-[TVICameraCapturePipeline startWithConsumer:configuration:]_block_invoke + 48
8   libdispatch.dylib                   0x0000000104a1e338 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x0000000104a1f730 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000104a26740 _dispatch_lane_serial_drain + 744
11  libdispatch.dylib                   0x0000000104a272e0 _dispatch_lane_invoke + 444
12  libdispatch.dylib                   0x0000000104a326c4 _dispatch_workloop_worker_thread + 1304
13  libsystem_pthread.dylib             0x00000001bd607b74 _pthread_wqthread + 272
14  libsystem_pthread.dylib             0x00000001bd60a740 start_wqthread + 8`

However just before the crash, i can see 'renderFrame' being invoked and i can get ImageData as a CImage.
Regarding TVIVideoRenderer, when does 'renderFrame' get invoked?  What triggers renderFrame to be invoked?

Would appreciate any inputs.
