### ISSUE TITLE
Error: Invalid Access Token Signature while connect Room

### ISSUE THREAD

**Issue by Nik20112** [twilio/video-quickstart-swift#146]
Hi,
I have generated access token from given php script and I am using this token for video call but while I am connecting the room that times its give me error like "Invalid Access Token Signature". Please help.
Php Code: Create Access Token:(Video) https://www.twilio.com/docs/api/rest/access-tokens

Thanks
Nikunj

**Comment by Nik20112** [comment]
Resolve due to wrong secret key. Used proper secret key and its working fine.

**Comment by ceaglest** [comment]
Hey @Nik20112,

Sorry for the lack of response here, but glad you were able to get things up and running.

Best,
Chris Eagleston
