### ISSUE TITLE
Issue: Twilio Video Call Kit not supported in iOS 8

### ISSUE THREAD

**Issue by Nik20112** [twilio/video-quickstart-swift#148]
Hi, 

Is there any tutorial or way to implement the twilio video call kit demo for iOS 8 and later? Please help me on this asap.

Thanks,
Nikunj

**Comment by ceaglest** [comment]
Hi Nikunj,

You came to the right place - we have an example of CallKit integration for Swift in this very repository.

https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart

However, Apple's [CallKit framework](https://developer.apple.com/documentation/callkit) is only available on iOS 10.0 or later.

Best,
Chris Eagleston

**Comment by Nik20112** [comment]
Hi,
But this is only work in iOS 10, right? Can I use this video call kit demo for invitation to other user for video calling? Is it possible in it or not?

**Comment by ceaglest** [comment]
Hi Nikunj,

Our CallKit example is scoped only to usage of the CallKit framework with Twilio Video, and uses local notifications for simplicity. The goal of the CallKit framework is not to provide a signaling mechanism for inviting users, but rather to provide your application with a first class calling experience similar to the Phone app. CallKit allows your video call to have the same priority as the Phone app, and other apps which use CallKit.

Consider our existing example's usage of local notifications a stub, where you can replace it with any signaling mechanism that you'd like. That being said the best way to invite another user to a video call is via push notifications. This is what you asked in the previous issue. https://github.com/twilio/video-quickstart-swift/issues/147

Regards,
Chris Eagleston

**Comment by Nik20112** [comment]
Thanks for the feedback. Only one way to invite user via push notification for video call? Hope, you will be provide demo asap for iOS like Android so we can integrate it in app.

Thanks

**Comment by ceaglest** [comment]
Hi Nikunj,

You can use any signaling channel that you'd like, however push notifications are the only thing that will work for iOS 10+ users while you application is not foregrounded. Lets continue this discussion in your other ticket, since I believe your original question about CallKit has been answered.

Regards,
Chris Eagleston
