### ISSUE TITLE
Network Handoff does not work in a Group Room

### ISSUE THREAD

**Issue by piyushtank** [twilio/video-quickstart-swift#154]
When Alice and Bob connected to a Group Room, if Alice's device switches to another network, her call to Bob, does not move to the new network seamlessly. Signaling works as expected but media stops working after the handoff.

Please note that this problem exists only for "Group" Rooms. For Peer-to-peer, hand off works as expected (i.e. Alice's media moves to the  new network seamlessly)

Our infrastructure team is working on fixing this problem and we are expecting to have this fixed soon. I will keep this ticket updated.

**Comment by ceaglest** [comment]
We're making some progress on this issue, but are not out of the woods yet. Ideally, we will land a Server side solution that is backwards compatible with 1.x and 2.x Clients, but there may be some Client betterments as well.

**Comment by ceaglest** [comment]
Hello,

Last week we deployed an update to our Media Servers which enables network handoff in Group Rooms. You do not need to update your Clients to take advantage of this fix.

However, we are still tracking some Client side betterments to improve our network handoff behavior across all Room types. For example, we are observing some cases involving ICE restart, and rollback which are not being handled properly.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

I've updated our [changelog](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x) to remove this as a known issue. We will still be working on the ICE restart betterments I mentioned but by and large network handoff in Group Rooms is now working.

Cheers,
Chris

**Comment by ceaglest** [comment]
Closing this as the original network handoff issues were resolved. We are tracking a remaining Wifi to Cell handoff issue in: https://github.com/twilio/video-quickstart-swift/issues/388
