### ISSUE TITLE
Adding audio effects?

### ISSUE THREAD

**Issue by sandbreaker** [twilio/video-quickstart-swift#157]
Is there a way to add AVAudioEngine to TVILocalAudioTrack? What I want to do is add audio effects (process real time) before it's added to TVILocalAudioTrack.

**Comment by ptankTwilio** [comment]
@sandbreaker Unfortunately video SDK does not have any API to add AVAudioEngine on TVILocalAudioTrack to add audio effects in real time. We are planning to improve our Audio APIs in future where we will consider supporting the used case. I apologize for the inconvenience.

**Comment by ceaglest** [comment]
Hi @sandbreaker,

You asked us about AVAudioEngine support, and adding audio effects to content shared via `TVILocalAudioTrack`. This should be doable using our AudioDevice APIs.

We've just released [2.0.0-beta1](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-beta1-february-7-2018) and an [example](https://github.com/twilio/video-quickstart-swift/tree/master/AudioDeviceExample) of a custom device. The initial version of the sample code doesn't use AVAudioEngine, but future iterations will.

Regards,
Chris Eagleston

**Comment by sandbreaker** [comment]
👍

**Comment by ceaglest** [comment]
@sandbreaker,

We've now added usage of AVAudioEngine to our TVIAudioDevice [example](https://github.com/twilio/video-quickstart-swift/tree/master/AudioDeviceExample).

Please give it a shot if you have some time. I'm going to close out this issue now that we've provided an answer to your original question.

Thanks,
Chris

**Comment by savasavic** [comment]
Is it possible to play mp3 file or there is a limit for the .caf file?
