### ISSUE TITLE
Background Incoming Call

### ISSUE THREAD

**Issue by manishgumbal** [twilio/video-quickstart-swift#158]
Unable to Manage Twilio call when app is in background please help. How to handle call when app is in background

I am creating a instance of callKit provider in app delegate to handle incoming call but after that I have to create a new instance in my view controller to handle video call.

How to get rid of this. Please help me to resolve this

**Comment by ptankTwilio** [comment]
@manishgumbal When your app is in the background, it needs to receive a push notification for the incoming call and the app should report incoming call to CallKit. Our [VideoCallKitQuickStart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart) demonstrate how to use TwilioVideo's CallKit APIs. The sample app does not demonstrate receiving the push notification, however, simulates the incoming call via UI, see [this](https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L137) for more information.

**Comment by ceaglest** [comment]
Closing as answered. Let us know if you need any more help with CallKit.
