### ISSUE TITLE
TwilioVideo 2.0.0-preview2 - Multiple errors on compiling - deprecated types/members?

### ISSUE THREAD

**Issue by nah2015** [twilio/video-quickstart-swift#169]
I'm guessing there is an update coming to your ViewController.swift files throughout your quickstart project?

I'm trying to find documentation on changes in 2.0.0 but I cannot find.

/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:256:46: Value of type 'TVIVideoTrackPublication' has no member 'removeRenderer'
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:256:46: Did you mean 'removeObserver'? (Foundation.NSObject)
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:256:46: Did you mean 'removeObserver'? (Foundation.NSObject)
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:285:13: Value of type 'TVIRoom' has no member 'participants'
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:286:32: Value of type 'TVIRoom' has no member 'participants'
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:287:29: Value of type 'TVIParticipant' has no member 'delegate'
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:287:29: Did you mean 'release'? (ObjectiveC.NSObject)
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:310:29: Value of type 'TVIParticipant' has no member 'delegate'
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:310:29: Did you mean 'release'? (ObjectiveC.NSObject)
/Users/n/Desktop/MYAPP/VideoQuickStart/ViewController.swift:324:28: Use of undeclared type 'TVIParticipantDelegate'

**Comment by paynerc** [comment]
Good morning!

Take a look at the [2.0.0-preview](https://github.com/twilio/video-quickstart-swift/tree/2.0.0-preview) branch. It has been updated for 2.0.0. Once 2.0.0 is released, we will merge that branch to master.

Hope this helps!

Ryan

**Comment by paynerc** [comment]
Also, the changelog for 2.0.0-preview2 can be found [here](https://www.twilio.com/docs/api/video/changelogs/ios).
Documentation for the 2.0.0-preview2 release can be found [here](https://media.twiliocdn.com/sdk/ios/video/releases/2.0.0-preview2/docs/).

Let us know if you need further assistance.

Ryan

**Comment by nah2015** [comment]
Thank you so much for the quick response Ryan.  You all do a good job with your support and docs.

Didn't notice the preview branch!
