### ISSUE TITLE
Call Failed Screen Appearing

### ISSUE THREAD

**Issue by deftsoftiphone** [twilio/video-quickstart-swift#170]
### Description

I am using Twillio with Callkit to use Video Call in my app. Whenever I try to cut the call from receiver end it shows me the Call Fail Screen. I used the code shown in your developer account and sample code but call fail screen is occuring at my end.

### Steps to Reproduce
1. User A Call User B using twillio and callkit in the app
2. User B picks the call and call started successfully
2. User B cut the call using the code, call fail screen apears

#### Code

```swift
    func performEndCallAction(uuid: UUID) {
        let endCallAction = CXEndCallAction(call: uuid)
        let transaction = CXTransaction(action: endCallAction)
        endCallAction.fulfill()
        callKitCallController.request(transaction) { error in
            if let error = error {
                NSLog("EndCallAction transaction request failed: \(error.localizedDescription).")
                return
            }
            
            NSLog("EndCallAction transaction request successful")
        }
    }
```

#### Expected Behavior

It should cut the call properly without getting the call failed screen

#### Actual Behavior

I am getting the call failed screen if it call ended by User B

#### Reproduces How Often

If happens every time I try to use this

**Comment by ptankTwilio** [comment]
@deftsoftiphone I tried to reproduce the problem by following the steps you have mentioned on our CallKit example quickstart app but I could not reproduce it. Can you answer following questions: 

1. Once user A and B are connected to a Room, if B hangs up the call, where do you see the "Call Failed" screen ? on user A's device or on user B's ?
2. Is it possible for you to reproduce the problem on CallKit QuickStart and share the code with us?

**Comment by deftsoftiphone** [comment]
Once user A and B are connected to a Room, if B hangs up the call, where do you see the "Call Failed" screen ? on user A's device or on user B's ?
In this case if A hangs up the call Call Fail Screen will appear on B

Can you make sure the code which connects to a Room matches with the Quickstart? Please make sure that both the users are able to connect to Room successfully.
Yes, Room is connected successfully

I noticed, in performEndCallAction you are fulfilling the endCallAction before the action gets performed. Like our quickstart app, you should fulfill the endCallAction when the action is performed.
That is changed but still facing same issue

Is it possible for you to reproduce the problem on CallKit QuickStart and share the code with us?

Right now, it is not possible for me to send code

This issue appears only if call cuts after 1 minute

**Comment by ptankTwilio** [comment]
@deftsoftiphone  I looked into the code you have provided and tried to simulate it in quickstart where app should performEndCall when remote participant hangs up the call. However, I am not able to reproduce the call failed screen. 

Can you try this and let me know if you could reproduce the CallFailed on my branch ? Here is the branch:  https://github.com/ptankTwilio/video-quickstart-swift/tree/try-reproduce-callfailed

**Comment by deftsoftiphone** [comment]
Thanks @ptankTwilio  it works now. Actual issue is I am moving to next view just right after end call due to which Callkit Provider goes nill without hanging up proper call.

Thanks for your support. I am closing this issue.

**Comment by RaziPour1993** [comment]
Close All Call :


     func performEndCallAction() {

        for call in self.cxCallController.callObserver.calls {
            
            let endCallAction = CXEndCallAction(call: call.uuid)
            let transaction = CXTransaction(action: endCallAction)
            
            cxCallController.request(transaction) { error in
                if let error = error {
                    NSLog("EndCallAction transaction request failed: \(error.localizedDescription).")
                    return
                }
                
                NSLog("EndCallAction transaction request successful")
                
            }
            
        }
        
    }

**Comment by ramohanreddy** [comment]
Hi @piyushtank 
when call end or call failed  no need to show the call end screen .
is it possible if yes how to do what can i do?

Thanks&Regards
Ramohan Reddy
