### ISSUE TITLE
Change previewView and remoteView position and frame runtime

### ISSUE THREAD

**Issue by vishalgabani** [twilio/video-quickstart-swift#174]
### Description

Hi,

I am using Twilio SDK to make video call for our application. I show local video in previewView and participant video in remoteView. previewView is fullscreen and remoteView is in small frame at first. I want to change position and size of previewView to remoteView and vice versa by tapping on view while video call is on.

Frame for previewView is CGRect(x: 0, y: 0, width: 375, height: 667)
Frame for remoteView is CGRect(x: 10, y: 60, width: 100, height: 145)

If I change frame for both views without autolayout, it works. I connect autolayout constraints via IBOutlet and When I change constants to change position and size, it does not change position or size. Am I missing anything here?

### Versions

All relevant version information for the issue.

#### Video iOS SDK

1.3.4 Manual installation

#### Xcode

8.3.3

#### iOS Version

8.0 to 10.3

#### iOS Device

iPhone 6S, iPad Mini 2

**Comment by ceaglest** [comment]
Hey @vishalgabani,

This is definitely possible to do with frame based layout, and I don't see any reason why it wouldn't work with auto layout either.

> If I change frame for both views without autolayout, it works. When I use autolayout via IBOutlet to change position and size, it does not change position or size. Am I missing anything here?

I'm not aware of how to dynamically update constraints using Interface Builder, but you can modify them programatically by changing the constants from an IBOutlet. Would you mind sharing the code where you update the constraints on the two views? I might be able to help out if there is something missing. Another option is to call `setNeedsUpdateConstraints`, and re-compute your constraints from there.

https://stackoverflow.com/questions/20609206/setneedslayout-vs-setneedsupdateconstraints-and-layoutifneeded-vs-updateconstra

Best,
Chris

**Comment by vishalgabani** [comment]
Hi @ceaglest 

Thank you for quick reply.

I think I missed some words for autolayout to make you understand. Yes, I connect autolayout constraint via IBOutlet but change it by giving value to constants.

#### Code

```swift
        self.localViewXConstraint.constant = 10
        self.localViewYConstraint.constant = 60
        self.localViewWidthConstraint.constant = 100
        self.localViewHeightConstraint.constant = 145

        self.remoteViewXConstraint.constant = 0
        self.remoteViewYConstraint.constant = 0
        self.remoteViewWidthConstraint.constant = 375
        self.remoteViewHeightConstraint.constant = 667

       //animatation to show moving
        UIView.animate(withDuration: 2.0, animations: {
            self.view.layoutIfNeeded()           
        },completion: nil)
```
Let me know if I miss anything here.

Thanks,
Vishal

**Comment by ceaglest** [comment]
Hi Vishal,

Thanks for sharing a code snippet. I'm not quite sure why the constraint changes aren't taking effect but I can dig into this a little more tomorrow.

Cheers,
Chris

**Comment by ceaglest** [comment]
Hey @vishalgabani,

Sorry for the delay on my side. I took the QuickStart and successfully modified it to dynamically change constraints on the remote `TVIVideoView`. You can find the branch [here](https://github.com/ceaglest/video-quickstart-swift/tree/issues/174).

What the code does is just shrink and enlarge the remote view while keeping the content centered, and animating the constraint changes.

```
    func flipCamera() {
        if (self.camera?.source == .frontCamera) {
            self.camera?.selectSource(.backCameraWide)

            // Make the remote video smaller!
            UIView.animate(withDuration: 2.0, animations: {
                self.remoteViewWidthConstraint?.constant = -100
                self.remoteViewHeightConstraint?.constant = -100
                self.view.layoutIfNeeded()
            })
        } else {
            self.camera?.selectSource(.frontCamera)

            // Make the remote video regular sized!
            UIView.animate(withDuration: 2.0, animations: {
                self.remoteViewWidthConstraint?.constant = 0
                self.remoteViewHeightConstraint?.constant = 0
                self.view.layoutIfNeeded()
            })
        }
```

I hope this is helpful in solving your autolayout question.

Regards,
Chris Eagleston

**Comment by ceaglest** [comment]
Hey @vishalgabani,

I hope this example was helpful, I know it made me laugh to watch the slow animations at least. 😆 

Since I haven't heard back from you I'm going to assume that you've solved this problem or moved on to something else. If you any more support on this issue free to re-open the ticket.

Best,
Chris Eagleston
