### ISSUE TITLE
 Facing video rendering and flickering issue in our iOS app

### ISSUE THREAD

**Issue by nfasate** [twilio/video-quickstart-swift#180]
### Description

Hello,
We have implemented and integrated Twilio Programmable Video SDK version 1.3.4 in our iOS application for Multi-Party video call.

We are using UICollectionView to render each connected participant of the room in a grid fashion. We have also tried adding 7 and more participants in our UICollectionView but while scrolling down to bottom and vice versa, videos of participants are freezing and flickering, sometimes it is leading us to app crash.

#### Code

```swift
// Here is our code snippet for adding multiple participants in UICollectionView -
func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell
{
        // get a reference to our storyboard cell
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "remoteCollectionViewCellID", for: indexPath) as! RemoteCollectionViewCell
        let participant = participantArray[indexPath.row]
        
        let fullArr = participant.identity.characters.split{$0 == "|"}.map(String.init)
        
        var participantName = participant.identity
        if fullArr.count > 0
        {
            participantName = fullArr[0]
        }
        
        cell.remoteUserNameLabel.text = participantName
        if cell.isVideoRender == true, participantArray[indexPath.row].videoTracks.count > 0
        {
            if participantArray[indexPath.row].videoTracks[0].renderers.count > 0
            {
                participantArray[indexPath.row].videoTracks[0].removeRenderer(cell.remoteFeedBaseView)
                participantArray[indexPath.row].videoTracks[0].addRenderer(cell.remoteFeedBaseView)
            }else {
                participantArray[indexPath.row].videoTracks[0].addRenderer(cell.remoteFeedBaseView)
            }
        }
        
        cell.layoutIfNeeded()
        return cell
}

func room(_ room: TVIRoom, participantDidConnect participant: TVIParticipant)
{
        participant.delegate = self
        participantArray.append(participant)
        logMessage(messageText: "\(participantName) " + NSLocalizedString("Joined", comment: ""))
 }

func room(_ room: TVIRoom, participantDidDisconnect participant: TVIParticipant)
{
        let idX = participantArray.index(of: (participant))
        logMessage(messageText: "\(participant.identity) " + NSLocalizedString("Left", comment: ""))
}

func participant(_ participant: TVIParticipant, addedVideoTrack videoTrack: TVIVideoTrack) 
{
        //logMessage(messageText: "Participant \(participant.identity) added video track")
        let idX = participantArray.index(of: (participant))
        self.remoteCollectionView.reloadData()
        self.scrollToLastItem()
}

```
Is there any way to resolve this issue, or what can be the best possible way to implement multi-party call in a grid fashion?

Awaiting your reply.

Thanks,
Nilesh

**Comment by ceaglest** [comment]
Hi Nilesh,

Thanks for writing in. We don't have sample code which demonstrates multi-party video layout yet, but we are planning on expanding our QuickStarts to do so. We do have an internal app which uses UICollectionView, so there are a couple of pointers that I can share:

> sometimes it is leading us to app crash.

At the moment our `addRenderer` API does not allow you to add the same renderer twice. If you do this an assertion will fire and crash your app. Is this what you are experiencing? I believe the code that you shared should take care of this:

```
        if cell.isVideoRender == true, participantArray[indexPath.row].videoTracks.count > 0
        {
            if participantArray[indexPath.row].videoTracks[0].renderers.count > 0
            {
                participantArray[indexPath.row].videoTracks[0].removeRenderer(cell.remoteFeedBaseView)
                participantArray[indexPath.row].videoTracks[0].addRenderer(cell.remoteFeedBaseView)
            }else {
                participantArray[indexPath.row].videoTracks[0].addRenderer(cell.remoteFeedBaseView)
            }
        }
```

If the issue is not adding a renderer twice then feel free to post a call stack and I'll have a look.

> We are using UICollectionView to render each connected participant of the room in a grid fashion. We have also tried adding 7 and more participants in our UICollectionView but while scrolling down to bottom and vice versa, videos of participants are freezing and flickering

The thing to keep in mind is that you are using `TVIVideoView` as a subview in of a `UICollectionViewCell`. Since the cell is reused, the renderer may go from rendering the content of one `TVIVideoTrack` to the content of another. Until the first frame from the new Track arrives you will see the last rendered frame from the previous one.

One thing that would help is reloading a specific cell, not the entire collection.

```
func participant(_ participant: TVIParticipant, addedVideoTrack videoTrack: TVIVideoTrack) 
{
        let idX = participantArray.index(of: (participant))
        // Only reload the cell that changes, not the entire collection.
        self.remoteCollectionView.reloadData()
        self.scrollToLastItem()
}
```

Another way to avoid flicker is to destroy the old renderer in your cell's `prepareForReuse` method.

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @nfasate,

Were you able to resolve issues with using UICollectionView and TVIVideoView together?

Regards,
Chris Eagleston

**Comment by nfasate** [comment]
Hi @ceaglest,

Yes, I have able to resolve video flickering issue using UICollectionView cell reuse method.

Thanks,
Nilesh

**Comment by HardikKardani** [comment]
i am facing same issue if you have collectionview demo then please share it

**Comment by Rushabh5** [comment]
> Hi @ceaglest,
> 
> Yes, I have able to resolve video flickering issue using UICollectionView cell reuse method.
> 
> Thanks,
> Nilesh

Hey @nfasate 

Can you please share the code?

Thanks

**Comment by ceaglest** [comment]
Hi @Rushabh5,

This is a very old issue and we've provided solutions for video flickering, and example code that uses a UICollectionView. Please open a new issue with more details about what is not working for you.

http://github.com/twilio/twilio-video-app-ios

Best,
Chris

**Comment by neerajwork20** [comment]
@ceaglest

Yes , but at least share the code one file so that we can see the how things have been working fine. Where things is lacking. I am facing flicking issue from long time, Please help.

https://github.com/twilio/twilio-video-app-ios

I have already checked above link many times, by downloading it and searching for collection-view but I could not able to find collection-view any implementation. If any solution found somewhere please point out similar solution file. 

Or , please share solution code here best one can also see , please help ASAP.

**Comment by Maaz-EmpGroup** [comment]
A little  bit effort from my side to achieve this but I am not guess to proper work.. Any one have better answer please share.. 

func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell:ParticipantsCollectionViewCell = self.collectionView.dequeueReusableCell(withReuseIdentifier: "ParticipantsCollectionViewCell", for: indexPath) as! ParticipantsCollectionViewCell
        
        let data = remoteParticipants[indexPath.row]
        if data.remoteVideoTracks[0].remoteTrack != nil{
            cell.remoteView = nil
            DispatchQueue.main.async {
                cell.setRemoteParticipant(remoteParticipant: data)
            }
        }
        return cell
    }
    
    #UICollectionViewCell Class
    
import UIKit
import TwilioVideo

class ParticipantsCollectionViewCell: UICollectionViewCell, VideoViewDelegate {

    @IBOutlet weak var imageBackgroundView: UIView!
    @IBOutlet weak var participantImageView: UIImageView!
    @IBOutlet weak var videoView: UIView!
    @IBOutlet weak var identityLabel: UILabel!
    
    @IBOutlet weak var emptyView: UIView!
    
    var remoteView: VideoView!
    override func awakeFromNib() {
        super.awakeFromNib()
        DispatchQueue.main.async {
            self.setupRemoteVideoView()
        }
        
    }

    func setRemoteParticipant(remoteParticipant: RemoteParticipant){
        
            if remoteParticipant.remoteAudioTracks[0].isTrackEnabled {
//                muteView.isHidden = true
            }else{
//                muteView.isHidden = false
            }
            if remoteParticipant.remoteVideoTracks.count == 0 {
                videoView.isHidden = true
                emptyView.isHidden = false
            }else{
                if remoteParticipant.remoteVideoTracks[0].isTrackEnabled{
                    videoView.isHidden = false
                    emptyView.isHidden = true
                    //screenshareView.isHidden = true
                    identityLabel.text = " \(remoteParticipant.identity)  "
                    emptyView.isHidden = true
                    if remoteView != nil{
                        remoteParticipant.remoteVideoTracks[0].remoteTrack!.addRenderer(remoteView)
                    }else{
                        self.setupRemoteVideoView()
                        DispatchQueue.main.async {
                            remoteParticipant.remoteVideoTracks[0].remoteTrack!.addRenderer(self.remoteView)
                        }
                    }
                }
            }
    }
    
    
    func setupRemoteVideoView() {
        // Creating `VideoView` programmatically
        self.remoteView = VideoView(frame: CGRect.zero, delegate: self)
        
        self.videoView.insertSubview(self.remoteView!, at: 0)
        
        // `VideoView` supports scaleToFill, scaleAspectFill and scaleAspectFit
        // scaleAspectFit is the default mode when you create `VideoView` programmatically.
        self.remoteView!.contentMode = .scaleAspectFill;
        
        let centerX = NSLayoutConstraint(item: self.remoteView!,
                                         attribute: NSLayoutConstraint.Attribute.centerX,
                                         relatedBy: NSLayoutConstraint.Relation.equal,
                                         toItem: self.videoView,
                                         attribute: NSLayoutConstraint.Attribute.centerX,
                                         multiplier: 1,
                                         constant: 0);
        self.videoView.addConstraint(centerX)
        let centerY = NSLayoutConstraint(item: self.remoteView!,
                                         attribute: NSLayoutConstraint.Attribute.centerY,
                                         relatedBy: NSLayoutConstraint.Relation.equal,
                                         toItem: self.videoView,
                                         attribute: NSLayoutConstraint.Attribute.centerY,
                                         multiplier: 1,
                                         constant: 0);
        self.videoView.addConstraint(centerY)
        let width = NSLayoutConstraint(item: self.remoteView!,
                                       attribute: NSLayoutConstraint.Attribute.width,
                                       relatedBy: NSLayoutConstraint.Relation.equal,
                                       toItem: self.videoView,
                                       attribute: NSLayoutConstraint.Attribute.width,
                                       multiplier: 1,
                                       constant: 0);
        self.videoView.addConstraint(width)
        let height = NSLayoutConstraint(item: self.remoteView!,
                                        attribute: NSLayoutConstraint.Attribute.height,
                                        relatedBy: NSLayoutConstraint.Relation.equal,
                                        toItem: self.videoView,
                                        attribute: NSLayoutConstraint.Attribute.height,
                                        multiplier: 1,
                                        constant: 0);
        self.videoView.addConstraint(height)
    }
}
