### ISSUE TITLE
How do i get who is speaking in current call . (detect the voice of person.identity  is speaking)

### ISSUE THREAD

**Issue by sunny1076** [twilio/video-quickstart-swift#181]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Github Issues](https://github.com/twilio/video-quickstart-swift/issues)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelogs/ios)

### Description

[Description of the issue]

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. [Insert as many steps as needed]

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

[What you expect to happen]

#### Actual Behavior

[What actually happens]

#### Reproduces How Often

[What percentage of the time does it reproduce?]

#### Logs

```
// Log output when the issue occurs
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.2.0 via CocoaPods]

#### Xcode

[e.g. 8.3.3]

#### iOS Version

[e.g. 10.3.3]

#### iOS Device

[e.g. iPhone 6s Plus]

**Comment by sunny1076** [comment]
Hi Chris, 

Please tell me that any solution for get who is speaking in current call .

Regards
Sunny

**Comment by ceaglest** [comment]
Hi @sunny1076,

Which version of the SDK are you using (perhaps 1.3.5, or 2.0.0-preview4)?

We don't offer a way to directly query an AudioTrack / RemoteAudioTrack for its audio level. However, there is another approach that could work which is to periodically call the `[TVIRoom getStats:]` API. By inspecting the reports you could determine which of the Remote Participant's Audio has the highest level.

Here is a code snippet to get you started using 1.3.5. My apologies for answering in Objective-C when you asked on the Swift QS repo, but this is adapted from an internal sample app.

```objc
- (void)statsTimerFired {
    typeof(self) __weak weakSelf = self;

    [self.room getStatsWithBlock:^(NSArray<TVIStatsReport *> * _Nonnull statsReports) {
        [weakSelf.statsProcessingQueue addOperationWithBlock:^{
            typeof(self) __strong strongSelf = weakSelf;

            if (strongSelf) {
                [strongSelf processStatsReports:statsReports];
            }
        }];
    }];
}

- (void)processStatsReports:(NSArray<TVIStatsReport *> *)statsReports {
    if ([statsReports count] == 0) {
        return;
    }

    for (TVIStatsReport *statsReport in statsReports) {
        for (TVIAudioTrackStats *remoteAudioTrackStats in statsReport.audioTrackStats) {
            NSUInteger audioLevel = remoteAudioTrackStats.audioLevel
            TVIParticipant *participant = [self participantForTrackId:remoteAudioTrackStats.trackId];

            // We now have the Participant and the volume level of it's audio track. Do something with it!
        }
    }
}

- (TVIParticipant *)participantForTrackId:(NSString *)trackId {
    NSArray *participants = self.room.participants;

    for (TVIParticipant *participant in participants) {
        NSArray<TVIAudioTrack *> *audioTracks = [participant audioTracks];
        for (TVIAudioTrack *audioTrack in audioTracks) {
            if ([audioTrack.trackId isEqualToString:trackId]) {
                return participant;
            }
        }
    }
}
```

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Hi @sunny1076,

Were you able to get speaker detection working using the `getStats:` APIs?

Regards,
Chris Eagleston

**Comment by sunny1076** [comment]
It is available this class api in swift also.

Regards
Sunny.

**Comment by ceaglest** [comment]
Yes, just like Apple's Objective-C frameworks everything in our SDK is available to your Swift applications.

**Comment by ceaglest** [comment]
Hey @sunny1076,

I'm going to close this ticket because I haven't seen any activity recently and I believe I answered your question with the code snippet above. If you're still stuck on this problem please re-open and I'd be happy to help further.

Thanks,
Chris
