### ISSUE TITLE
 How can I clear the frame of a previous call from videoView that conforms to class TVIVideoView ?

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#183]
I am using, Twilio Video Swift Quickstart

I am rendering a video track (for a video call) using UIView that conforms to class TVIVideoView.

When the video call ends, I am hiding videoView, when the call is about to start again, I am unhiding the videoView which displays the last frame from previous call. **How can I clear the frame of previous call from videoView ?**

The below is what I am doing, to start and stop rendering the video track, taken from Twilio-Video-QuickStart-Swift.

    // To start rendering videoTrack
    videoTrack.addRenderer(self.videoView)

    // To stop rendering videoTrack
    videoTrack.removeRenderer(self.videoView!)

`videoTrack` conforms to class TVIVideoTrack.

Question also posted on [StackOverflow](https://stackoverflow.com/q/46583055/2534233)

**Comment by phucnm** [comment]
Hi,

As you can see in the sample project, they init a new instance of TVIVideoView to render video stream.

So rather thinking about clearing the frame, just remove the unused videoView from superView and then create a new one whenever you need, that's also a good approach because you may use the property "hasVideoData" of TVIVideoView to do something in the future.

**Comment by ceaglest** [comment]
Hey @pravishanth,

As @phucnm mentioned the best approach at this point is to not reuse the TVIVideoView between calls. We don't provide any method to clear the previous frame, but this may be useful for some cases, especially cell reuse in a UICollectionView / UITableView.

https://github.com/twilio/video-quickstart-swift/issues/180

Regards,
Chris Eagleston

**Comment by pravishanth** [comment]
By following @phucnm advice helped to resolve the issue.
