### ISSUE TITLE
Can I play recorded video or audio in browser(UIWebView) using "recording SID

### ISSUE THREAD

**Issue by Abhisheksnapwiz** [twilio/video-quickstart-swift#185]
**Description**

I have recorded SID for both audio and video and When I am trying to play the Video or Audio using recording SID in browser It's asking me to authenticate and after authentication Video or Audio file is getting downloaded Instead I am looking to stream and play the Audio or Video when hit the url in browser or pass it to UIWebView.

Please share url formate where we can stream the video without asking the authentication popup(where we can add username and password in url).

This is because after recording video from my IOS App I need to play the video in UIWebview. First I am trying to play it in browser but instead of playing recorded video(Streaming) It's getting downloaded.

I am using url as -
Video -
https://video.twilio.com/v1/Recordings/RTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Media
Audio -
https://video.twilio.com/v1/Recordings/RTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

About Twilio use -
Product - Programmable Video

Twilio Helper Library or SDK for server side(Node js)-

JavaScript SDKs/Video/JavaScript
https://www.twilio.com/docs/api/video/download-video-sdks#javascript-sdk
npm install --save twilio-video

I am running local server to get access token, Create room and get recording SID's(Audio and video both).

**Comment by ptankTwilio** [comment]
@Abhisheksnapwiz Can you provide more details about your dev setup and the used case you are trying to achieve? From your note, it seems that you are expecting iOS Swift Callbacks while using the JavaScript SDK in your app? Please note that Video SDK is available in JavaScript SDK for web applications and iOS SDK for iOS Objective-C and Swift Application. At present JavaScript SDK is not supported for Swift, however, I encourage you to try out our iOS Video SDK for Swift application.
Thanks and let me know if you have any questions.

**Comment by Abhisheksnapwiz** [comment]
@ptankTwilio   - Dev Setup
**Server**
I am running Node.js code on server side to generate the Access token and create the room and this I am running at my local machine

**Device -** 
I have took reference from [video-quickstart-swift] (https://github.com/twilio/video-quickstart-swift). 
Once group room with  got created on server
