### ISSUE TITLE
StartCallAction transaction request failed, CallKit.error.requesttransaction error 7

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#187]
Occasionally,  when I make a video call I get the below error, why could this be ?

StartCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 7.)

I've modified `twilioVideoCallKitQuickstart` sample app from Github and used it in my app.

**Comment by pravishanth** [comment]
Call kit error 7 means: maximumCallGroupsReached, The requested transaction contains actions that, if performed, would exceed the maximum number of call groups for the provider.


Was getting this issue since I did not end the previous calls properly. The issue is resolved after ending the call properly.

**Comment by ceaglest** [comment]
Hi @pravishanth,

It's great to hear that you were able to resolve the call management issue! Sorry for the late response on our end.

Regards,
Chris

**Comment by tragicmj** [comment]
Getting the same issue, when trying to place a call for the first time.
