### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by moh1122** [twilio/video-quickstart-swift#19]
Hey
I got 2 errors while building this project any clue ?

**Comment by idelgado** [comment]
@moh1122 what were the errors you got? We've since moved to a new version of the SDK. I encourage you to try it and hopefully you won't see any errors.

https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk

**Comment by idelgado** [comment]
Please reopen the issue if you can provide more information about the errors. Sorry we did not respond in a timely manner.
