### ISSUE TITLE
Call fails when call kit switches from old call to new call

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#191]
Hi,

I have a scenario where, 
1. Caller initiates the call
2. Receiver accepts the call (from call kit screen)
3. Due to network issue caller could not connect to the room while the receiver gets connected to the room 
4. Caller disconnects the call and initiates new call
5. Receiver who has already connected to the room gets a new incoming call. Call kit screen prompts to end and accept new call.
6. When the receiver ends (old call) and accepts the new call (from call kit screen), call fails.

I am using TwilioVideoQuickstartCallkit in my app.

**Comment by ptankTwilio** [comment]
@pravishanth Thanks for reaching out. I am assuming you are initiating `TwilioVideo.connect` when you are accepting the new call on the receiver side. Can you make sure the app received the didConnectToRoom callback? If not, can you post the received error via`didFailToConnectToRoom` callback?

**Comment by pravishanth** [comment]
1. When the receiver receives the call the below function gets called, which triggers native call screen.
`function reportIncomingCall(uuid: UUID, roomName: String?, callerName: String, completion: ((NSError?) -> Void)? = nil)`

2. On accepting the call from call kit screen, `CXAnswerCallAction` gets triggered which then calls 
`performRoomConnect(uuid: action.callUUID, roomName: callerRoomName) { (success) in`

For step 6, `When the receiver ends (old call) and accepts the new call (from call kit screen)`, the old call on the receiver gets disconnected, but the new call on the receiver doesn't get started.
The following delegate methods are triggered `performEndCallAction ` &  `performAnswerCallAction `

I guess I am removing videoViews on ending the call and perhaps the views are not setup the second time.

I will further investigate the issue and report back.
 
Thanks for your right questions!!

**Comment by piyushtank** [comment]
@pravishanth I am closing the ticket but feel free to re-open if you are still observing the issue.
