### ISSUE TITLE
How will the caller know when the receiver declines the call from CallKit screen

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#195]
1. Is there  a delegate method that would be called in the caller app when the receiver declines the call from CallKit screen ?

How would the caller know that the receiver declined the call ?

2. Is it wise to automatically disconnect the caller from the room if the remote participant does not connect to the room in certain time (may be 3 mins). This is to ensure that the caller does not wait for endless period of time.

I am using TwilioVideoQuickstartCallkit in my app.

**Comment by ptankTwilio** [comment]
@pravishanth The answer to this question depends on your signaling implementation. Here is one way how you could achieve it-

Scenario:  "Alice calls Bob and Bob rejects the call"  

1. Alice connects to a Room using TwilioVideo API
2. Assuming your app have a signaling implemented, notify Bob about the incoming call.
3. Bob rejects the call, your signaling should notify Alice's app about this.
4. When Alice receives the notification that Bob has rejected the call, Alice initiates disconnect to Room using TwilioVideo API and then your app should trigger `CXEndCallAction`. 

Let me know if you have any questions.

**Comment by pravishanth** [comment]
Thanks for the tip, will implement this in the client and signalling server.

**Comment by pravishanth** [comment]
@ptankTwilio, Do you have any advice or tips for implementing signalling for video call ? Would really appreciate your guidance.
I am using Firebase realtime database to implement signalling or are there any better alternatives ?

**Comment by ptankTwilio** [comment]
@pravishanth [Twilio Sync](https://www.twilio.com/docs/api/sync) is a great solution to implement signaling for video call. I recommend trying it.

**Comment by VishalSharma91** [comment]
Hi @piyushtank I am calling API when a receiver declines the call in its  CXEndCallAction, when app is in background, phone locked or app is killed. This way the sender would get a push notification for same. But the api doesn't get called may be due to some limitation of Callkit? Can you please guide here ?

**Comment by piyushtank** [comment]
@VishalSharma91 When a VoIP push notification is received if an app is killed or device is locked, iOS will still deliver the push notification to your app and invoke `pushRegistry:didReceiveIncomingPushWithPayload:withCompletionHandler:`. Based on user's action accept or reject, app CallKit would give a Callback to app.
