### ISSUE TITLE
Call Disconnected Automatically

### ISSUE THREAD

**Issue by deftsoftiphone** [twilio/video-quickstart-swift#197]
### Description

I am using the Twillio CallKit for video calling in my app. It is working fine for every case but sometimes call disconnected automatically, while internet is working fine.

### Steps to Reproduce

1. User A calls User B
2. User B picks the call
3. After some time approx. 10-15 minutes of time call disconnected sometimes.
4. After this I am unable to connect with the same user untill I switch of my Phone and connect with user again.

#### Expected Behavior

Call should not disconnect automatically.

#### Actual Behavior

Call disconnected sometimes automatically

#### Reproduces How Often

20-30%

### Versions

Latest Twillio Version

#### Xcode
8.3.3
#### iOS Version
10.3.3
#### iOS Device
iPhone 6s

**Comment by ceaglest** [comment]
Closing, we didn't have enough information to follow up on this ticket. Let us know if this is still a problem with the latest 1.3.9, or 2.0.0-preview8 releases. If you have a recent example where the disconnect is occurring please re-open and provide a Room SID `TVIRoom.sid` and we will have a look.

**Comment by hand228** [comment]
@ceaglest 
Hi there,
I have the same issue with the owner of this thread. In my case, call was disconnected after 1 min 40s. Could you help me with this?
My Call Sid is `RMe8a27fb5a0fc9ca3fbce3e5a82f876ff`
