### ISSUE TITLE
Can I change default AVAudioSessionCategoryOptions?

### ISSUE THREAD

**Issue by yukitoto** [twilio/video-quickstart-swift#206]
I want to set `mixWithOthers` of AVAudioSessionCategoryOptions, but sdk set without options.
If I set options by myself, SDK override this.

**Comment by ptankTwilio** [comment]
@yukitoto At present, our existing API does not support allow configuring audio session category options explicitly. Internally we are discussing providing better audio APIs. However, In the meantime, you can work around the problem and set `AVAudioSessionCategoryOptions`  by using our CallKit APIs. Our [AVPlayerExample](https://github.com/twilio/video-quickstart-objc/tree/master/AVPlayerExample) how to configure audio session using Video SDK's CallKit APIs.

I have created a [branch](https://github.com/ptankTwilio/video-quickstart-objc/tree/category-option-mix-with-others) for you on AVPlayerExample 2.0.0-preview which demonstrates how to set AVAudioSessionCategoryOptions to `mixWithOthers` while using the Video SDK.

See this commit - https://github.com/ptankTwilio/video-quickstart-objc/commit/5cfbef977f0a46f69250f81901e3a0c69583bf8b

Let me know if you have any questions.

**Comment by ptankTwilio** [comment]
@yukitoto We have just released 2.0.0-preview8 with new Audio APIs. The 2.0.0-preview8 provides a block property in TVIDefaultAudioSession class. You can configure AVAudioSession of your choice inside the block and SDK will not overwrite the configuration.

2.0.0-preview8 Changelogs - https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-preview8-january-9-2018

Few example usages: 
https://github.com/twilio/video-quickstart-objc/tree/2.0.0-preview/AVPlayerExample
https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart

I would recommend using 2.0.0-preview. Let me know if you have any questions.

**Comment by ceaglest** [comment]
@yukitoto hopefully you were able to resolve this issue with the `TVIDefaultAudioDevice` APIs. I'm going to close this issue, but please re-open if you need more help with this.
