### ISSUE TITLE
TVIParticipantDelegate methods are not being called when call is initiated second time

### ISSUE THREAD

**Issue by pravishanth** [twilio/video-quickstart-swift#209]
Hi,

Scenario: 
1. Alice calls Bob
2. Alice and Bob connect and start a video call
3. Alice disconnects call
4. Alice calls Bob
5. **Alice cannot see Bob's video** but can only hear, While Bob can hear and see Alice

Since I have implemented signalling for Alice & Bob to communicate each others state before handshake. I am having this issue where Alice cannot see Bob's video.

I found that `TVIParticipantDelegate` methods in Alice are not being called when Alice calls Bob second time (step 4) (preceding which Alice had disconnected call the first time).

@ptankTwilio, Could you please give me some pointers as how I could possibly fix the issue ? or what I should be looking for ?

The issue doesn't appear if Bob had disconnected the call previously.

Using TwilioVideo 1.0.0

iOS: 10.3.3

Device: iPhone 5

Thanks
Pravishanth

**Comment by ptankTwilio** [comment]
@pravishanth Are you able to reproduce the problem on QuickStart? On your app, I will make sure - 
1. All objects associated with the first call is cleaned up properly.
2. For second call, make sure the `TVIRoomDelegate` is set properly and `TVIRoomDelegate` events are received on both sides.
3. For second call, make sure the `TVIParticipantDelegate` is set properly and `TVIParticipantDelegate` events are received on both sides.

Also, TwilioVideo's 2.0 preview release is available. You can try it out. Here are the changelogs- https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-preview7-november-9-2017

Let me know if you have any questions.

**Comment by ceaglest** [comment]
Hi @pravishanth,

> Using TwilioVideo 1.0.0

If you're set on using our 1.x releases that's okay but please use 1.3.8. Otherwise Piyush linked to 2.0 above.

1.3.8 - https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-1x#138-november-6-2017

Best,
Chris

**Comment by ceaglest** [comment]
Hey @pravishanth,

> @ceaglest, I've updated to TwilioVideo to 1.3.8.
I was assuming I might have to change methods and rewire the app if I switch to TwilioVideo 2.0, would you recommend to update to 2.0 in production environment ?

Overall, our 2.0-preview releases are much more stable than our original 1.0-betas were and offer quite a few useful features. You can find a summary on our getting started page:

https://www.twilio.com/docs/api/video/ios#preview-releases

That being said we are still planning a few API changes before we hit 2.0.0-beta1.

* Track subscription errors.
* AVAudioSession management (TVIAudioController, and CallKit APIs).
* Codec preferences tweaks.

It may take some small effort to keep up with the changes, so if you don't have time for that right now I would recommend staying on 1.x. Once we hit beta1 we would like to confine our API changes to be additive only.

Regards,
Chris
