### ISSUE TITLE
ETA for 2.0 release?

### ISSUE THREAD

**Issue by betzerra** [twilio/video-quickstart-swift#213]
_It's very likely this is not the place to ask this question, but honestly I didn't know where to ask._

Hi guys, do you have an ETA of when 2.0 is going to be released? 

Our team is thinking about checking out 2.0 and migrate our code but that depends on how stable current version is and how much time is left for the release candidate. 

Thanks in advance

**Comment by ceaglest** [comment]
Hi @betzerra,

> It's very likely this is not the place to ask this question, but honestly I didn't know where to ask.

We've recently started publishing our releases to [twilio-video-ios](https://github.com/twilio/twilio-video-ios/releases), and will be encouraging developers to file SDK specific issues there going forward.

> Hi guys, do you have an ETA of when 2.0 is going to be released?
>
> Our team is thinking about checking out 2.0 and migrate our code but that depends on how stable current version is and how much time is left for the release candidate.

Our 2.0.0-preview releases are fairly stable right now, but there are a few known issues mentioned in our [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-preview7-november-9-2017). The 2.0.0-preview8 release out next week will have a few more API changes, and some bug fixes / stability improvements.

After that, we are aiming to release 2.0.0-beta1 by the end of the month. We hope to keep the beta period relatively short, but this will depend on the customer feedback that we receive. I'd say its reasonable to expect that we will be out of beta with a 2.0.0 Generally Available (GA) release by the end of Q1 2018.

Best,
Chris Eagleston

**Comment by betzerra** [comment]
Thank you so much @ceaglest 
I appreciate your fast reply :-)

Cheers,
Ezequiel Becerra
