### ISSUE TITLE
Know which Participant is currently speaking?

### ISSUE THREAD

**Issue by PorterHoskins** [twilio/video-quickstart-swift#217]
Given a list of `TVIRemoteAudioTrack`, how do I know which track is currently sending data? Is there a way to know which participant is actively speaking?

**Comment by ceaglest** [comment]
Hi @PorterHoskins,

Sorry for the delayed response. We don't have example code which shows active speaker detection on the client side but there is a previous issue where I provided code snippets to do this. Please have a look and let us know if there is any more we can do to help.

https://github.com/twilio/video-quickstart-swift/issues/181

Best,
Chris

**Comment by ceaglest** [comment]
Hi @PorterHoskins,

Were you able to get the help you needed with the information in the other ticket?

Regards,
Chris

**Comment by PorterHoskins** [comment]
Looks like I can probably figure it out based on that. Thanks
