### ISSUE TITLE
(2.0.0-preview8, preview9) Audio stops working if the user receives incoming GSM call while in Room.

### ISSUE THREAD

**Issue by piyushtank** [twilio/video-quickstart-swift#221]
### Description

Audio stops working if the user receives incoming GSM call while in Room.

### Steps to Reproduce

1. Alice and Bob are in a room. Alice and Bob can hear each other in Room.
1. Alice receives incoming GSM call on the native iPhone dialer. Alice rejects the GSM call.
1. iPhone shows Alice's app again. Alice is connected to Room but Alice and Bob cannot hear each other.

#### Code

NA

#### Expected Behavior

Alice and Bob should be able to hear each other.

#### Actual Behavior

Audio stops working.

#### Reproduces How Often

100%

#### Logs

NA

#### Video iOS SDK

Video SDK 2.0.0-preview8
Video SDK 2.0.0-preview9

#### Xcode

NA

#### iOS Version

iOS 9+

#### iOS Device

All iPhones

**Comment by piyushtank** [comment]
We are working on fixing this issue and hoping to have the Video SDK with the fix released in a few days. You can work around this problem by using CallKit in your app.
Sorry for the inconvenience caused by this bug.

**Comment by ceaglest** [comment]
Once again we're sorry about introducing this regression. We expect to release `2.0.0-beta1` tomorrow which will resolve the bug.

**Comment by ceaglest** [comment]
We are live with [2.0.0-beta1](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-beta1-february-7-2018) which fixes regressions in interruption handling.

**Comment by ceaglest** [comment]
Closing now that the fix is widely available.
