### ISSUE TITLE
Audio lost after caller receives a call from other app and Callkit is openned

### ISSUE THREAD

**Issue by BorjaCloobing** [twilio/video-quickstart-swift#231]
### Description

When 2 users are in the middle of a conversation and "the caller" receives a new call from another app or its own phone, after hang it up, sound is muted for my online twilio call. Futhermore if we do the same exercise but is "the receiver" who receives the call, it works as it should be, i guess is because callkit configuration in my app is set up properly. But there is no way to configure for "the caller"

### Steps to Reproduce

User A calls user B
User B answers
User A receives a normal call from his phone (callkit is opened to answer or cancel this new call)
User A hang up this new call 
When user A goes back to conversation with user B, call is still alive but they both don't hear anything

#### Expected Behavior

Audio should not be muted when another app is calling and not even answered it

#### Actual Behavior

When caller receives an external call in the middle of a Twilio call, no matter if caller answers or hang up the new call, that twilio call is automatically muted once callkit screen is opened to the caller to treat that new call.

#### Xcode

9.0

#### iOS Version

11.2.6

#### iOS Device

iphone 6

**Comment by ceaglest** [comment]
Hi @BorjaCloobing,

Which version of Twilio Video are you using? We've fixed some issues with interruptions that existed in 2.0.0-preview8 and 2.0.0-preview9 in [2.0.0-beta1](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-beta1-february-7-2018).

Is the issue reproducible in our example CallKit application?

Best,
Chris Eagleston

**Comment by BorjaCloobing** [comment]
Hi @ceaglest 

The problem is happening with Twilio Voice, i am also implementing Twilio Video but it works good in this case.

Using TwilioVideo (1.3.10)
Using TwilioVoice (2.0.1)

**Comment by ceaglest** [comment]
Hi @BorjaCloobing,

I'm sorry to hear that you're having audio problems with TwilioVoice. Would you mind filing an issue in: https://github.com/twilio/voice-quickstart-swift/issues so that our Voice team can help you out?

Thanks,
Chris

**Comment by BorjaCloobing** [comment]
done

**Comment by ceaglest** [comment]
Thanks, closing the video issue in favor of: https://github.com/twilio/voice-quickstart-swift/issues/116
