### ISSUE TITLE
Bluetooth Earphones not working on Video Call

### ISSUE THREAD

**Issue by mavericksunny** [twilio/video-quickstart-swift#236]
### Description

When you connect bluetooth earphones to the iOS device (eg. airpods ), there is no audio received or transmitted from the earphone and its microphone.

### Steps to Reproduce

1. Pair and connect your bluetooth earphones to the iOS device
2. Open the video-quickstart app 
3. Connect to the room with an existing participant

#### Expected Behavior

Audio should be received and sent from the bluetooth earphones

#### Actual Behavior

No audio is sent or received in the bluetooth earphones

#### Reproduces How Often

100%

#### Logs

https://github.com/twilio/video-quickstart-swift/files/1796498/twilioAirpods.log

### Versions

All relevant version information for the issue.

#### Video iOS SDK

2.0.0-beta2

#### Xcode

9.2
#### iOS Version

11.0

#### iOS Device

iPhone 5S

**Note: It works fine on SDK version 1.x. But it does NOT work on SDK 2.x**

**Comment by piyushtank** [comment]
@mavericksunny Thanks for reaching out to us. In my experience, I have not noticed this problem while switching the audio route between microphone and bluetooth, I have asked QA team to do more validation for this case. In the meantime, in order to help debug the problem, is it possible for you to enable media engine (webrtc) logs and upload? Following is the code snippet to enable the webrtc logs - 

`TwilioVideo.setLogLevel(.debug, module: .webRTC)`

**Comment by mavericksunny** [comment]
@piyushtank Please find the logs as requested
[twilioAirpodsWebRTC.log](https://github.com/twilio/video-quickstart-swift/files/1801777/twilioAirpodsWebRTC.log)

**Comment by piyushtank** [comment]
@mavericksunny Thanks for providing the logs, we will look into the logs. Also, our QA is able to reproduce the bug you have observed. We will fix the problem as soon as possible and let you know. I am sorry for the inconvenience.

**Comment by ceaglest** [comment]
Hi,

This audio scenario should work properly in 2.0.0-beta3 (out tomorrow). Thanks for reporting the bug to us, it is greatly appreciated.

Cheers,
Chris

**Comment by ceaglest** [comment]
We are now live with [2.0.0-beta3](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x#200-beta3-march-21-2018) which resolves this bug.

**Comment by sdenardi** [comment]
@ceaglest Great, thank you so much!

**Comment by ceaglest** [comment]
Closing this one out. Please let us know if there are any more bluetooth related issues.
