### ISSUE TITLE
Calkit speaker is getting disabled

### ISSUE THREAD

**Issue by hasgar** [twilio/video-quickstart-swift#239]
Integrated twilio video calling with callkit. After answering an incoming call most of the times speaker is getting disabled in callkit, video is working fine. But, others in the room can't hear the sound from the app and can't hear sound of others in the app too. audio subcribed function not firing too.

TwilioVideo: 2.0.0-beta2'
iOS : 10.3.3

NB: I think this started occurs after using mute functionality. i'm not sure

**Comment by paynerc** [comment]
@hasgar 

Are you experiencing this issue in the CallKit sample app or in your own application? Also, can you provide a Room SID so I can research why the audio subscription callbacks are not being fired?

**Comment by hasgar** [comment]
No..in sample app it is working fine..how can i get the room sid?

**Comment by paynerc** [comment]
@hasgar,

After you connect to a room, you can query the [`sid`](https://twilio.github.io/twilio-video-ios/docs/2.0.0-beta2/Classes/TVIRoom.html#//api/name/sid) property on the `TVIRoom` object.

Ryan

**Comment by hasgar** [comment]
Could you please check details of these three room id details
RMf1cdf039ad90fc3534f0e049e3bce69a
RM8e55681b1373a1fbfa207648932d830c
RMf3bfdf51da3c7c78df450c782aab86b6

**Comment by paynerc** [comment]
@hasgar,

Quick question, I have looked at the traffic for the above rooms and only ever see one participant in the room. Do you have examples where there is another participant in the room that is unable to hear the audio?

Ryan

**Comment by hasgar** [comment]
RM63d26e1ebdee86f42c387163cdd2c8bf - 'identity' is the identity of the app.. in this room audio doesn't work.. but RM94015337412c6c7db94faed197565c8c in this room audio works perfect.. because when call happening in the first room i pressed mute button few times.. i think its all related to that mute function. i used the same function as quick start..and i didn't check the mute functionality in quick start..don't know quick start also have problem.. any thoughts?

**Comment by paynerc** [comment]
@hasgar,

I will take some time today and test muting on the CallKit Quickstart app and see if I can reproduce the issue you are seeing. I will let you know if I am able to reproduce it.

Thanks!

Ryan

**Comment by hasgar** [comment]
I just set AVAudioSession to AVAudioSessionCategoryPlayAndRecord in answering call function..now its working

**Comment by paynerc** [comment]
@hasgar 

From your previous comment, it appears that you hav this working and all is well. If you have any further issues, don't hesitate to reach out!

Ryan
