### ISSUE TITLE
Echo cancellation does not work on iPad Pro 12.9" (2017)

### ISSUE THREAD

**Issue by piyushtank** [twilio/video-quickstart-swift#241]
### Description

Echo Cancellation does not work properly on the iPad Pro 12.9" (2017).

### Steps to Reproduce

1. Alice joins a Room on iPad Pro 12.9" (2017).
2. Bob joins the Room from his iPhone
3. When Bob speaks, he can hear himself.

#### Expected Behavior

Bob should not get an echo when he speaks.

#### Actual Behavior

Bob gets an echo when he speaks.

#### Reproduces How Often

100%

#### iOS Version

iOS 11.3 Beta3 and prior

#### iOS Device

iPad Pro 12.9" (2017) only

**Comment by piyushtank** [comment]
This problem is not reproducible on iOS 11.3 Beta5.

**Comment by ceaglest** [comment]
Hello,

One workaround for this device specific bug is to use software echo cancellation. At the moment our iOS builds don't expose this feature, and we rely solely on Apple's AudioUnit echo cancellation solution. We are considering adding software echo cancellation to our iOS SDK, but we are also pleased that Apple has resolved the problem with this iPad model in the forthcoming iOS 11.3 update.

Regards,
Chris

**Comment by ceaglest** [comment]
Closing now that iOS 11.3 has been available for some time. We don't have any near term plans to add a software echo cancellation option, but we are considering doing this post 2.0.

**Comment by malavagile** [comment]
Hello @ceaglest ,

I am facing the same issue currently which @piyushtank raised previously.

I have just updated my Twillio iOS SDK Version to 2.7 but still, I am able to hear my self.

I have check out that there is an option to enable software cancellation from localAudioTrack but somehow I am not able to set those options. Can you check it out and let me know where I am going wrong.

I couldn't find a way to enable it. 

I tried to use the class directly and with a wrapper class as well.

I have tested it with **iOS 12.1.4** on **iPhone 6S Plus and iPhone X.**

![screenshot 2019-02-26 at 3 07 12 pm](https://user-images.githubusercontent.com/10988932/53402704-3c5da500-39d8-11e9-95ba-5851dfc7d05a.png)
