### ISSUE TITLE
Video is blinking while App is online and only Local Video but on other side Remote App is working Fine

### ISSUE THREAD

**Issue by nomimalik1769** [twilio/video-quickstart-swift#242]
I am having issue while using Twilio video SDK Every thing else is working fine but whenever I am going online Local video track is blinking anyone have faced this issue please help me out and if you need any type of code i will post it just comment out what section of code you want.

```
func startPreview() {
        if PlatformUtils.isSimulator {
            return
        }
        camera = TVICameraCapturer(source: .frontCamera, delegate: self)
        let videoConstraints = TVIVideoConstraints { (constraints) in
            constraints.maxSize = TVIVideoConstraintsSize640x480
            constraints.minSize = TVIVideoConstraintsSize480x360
            constraints.maxFrameRate = TVIVideoConstraintsFrameRate30
            constraints.minFrameRate = TVIVideoConstraintsFrameRate10
        }
       localVideoTrack = TVILocalVideoTrack.init(capturer: camera!, enabled: true, constraints: videoConstraints, name: "Camera")
        if (localVideoTrack == nil) {
            print("Failed to create video track")
        } else {
            localVideoTrack!.addRenderer(self.CameraView)

        }
    }
```

**Comment by ceaglest** [comment]
Hi @nomimalik1769,

Are you by any chance adding `self.CameraView` as a renderer multiple times? That's the only obvious thing I can think of that would cause the flickering that you describe.

Is the same issue reproducible for you in the QS app?

What version of the SDK?

What device?

What OS version?

Best,
Chris

**Comment by nomimalik1769** [comment]
I am adding video renderer in two places one is when I am going online and the other is this function tell me if I am doing this wrong Thank You.

```
 func subscribed(to videoTrack: TVIRemoteVideoTrack,
                    publication: TVIRemoteVideoTrackPublication,
                    for participant: TVIRemoteParticipant) {
        
        if (self.remoteParticipant == participant) {
            videoTrack.addRenderer(self.CameraView!)
        }
    }
```

**Comment by ceaglest** [comment]
Hi @nomimalik1769,

Sorry that I did not reply to your question.

It looks like you are adding `self.CameraView` as a renderer of both `localVideoTrack` and up to one remote Participant. You should create one TVIVideoView for each TVIVideoTrack that you want to display on screen. The regular [QuickStart example](https://github.com/twilio/video-quickstart-swift/tree/master/VideoQuickStart) demonstrates how to do this.

Best,
Chris

**Comment by nomimalik1769** [comment]
Actually, this was not the issue and also not at my end actually I was connecting my App with android mean we are working on Android and iOS both same APP and the fault was on that end and it's been solved anyway. Thank You for your reply.

**Comment by harleenchauhan** [comment]
Hlo 
I am facing fliker issue in case of video call in twilio Help me to solve this.
