### ISSUE TITLE
No such module `TwilioVideo`

### ISSUE THREAD

**Issue by richardtop** [twilio/video-quickstart-swift#249]
1. Open `VideoQuickStart` project
2. Try to compile

**Comment by paynerc** [comment]
Hey @richardtop,

Did you run `pod install` first? Once that is done it will create an Xcode Workspace file that you can open and the TwilioVideo framework will be there.

Thanks,

Ryan

**Comment by richardtop** [comment]
@paynerc Thanks for the suggestion!
Didn't notice the `podfile` in the folder.

**Comment by paynerc** [comment]
No worries! Glad you got it working!

**Comment by wazzah-marham** [comment]
worked for me as well (y)
