### ISSUE TITLE
Error Creating Remote Tokens

### ISSUE THREAD

**Issue by EricMwangi** [twilio/video-quickstart-swift#250]
@ceaglest 

### Description

Error configuring access tokens remotely 

### Steps to Reproduce

1. I downloaded quickstart and configured it using the steps mentioned in the README.md file
2. I generated two access tokens using the testing tools page and used one of them to run the program in the simulator and the other in an iPhone 5S
3. I was able to enter the room with both the simulator and the phone and it worked perfectly
4. I installed the php "Video access token server" and by typing (http://localhost:8000?identity=alice&room=example) in my web browser I was able to see what looks like an access token
5. I installed ngrok and was able to tunnel the localhost
6. I was able to see what looks like an access token by replacing localhost:8000 with my ngrok url which had this format (https://b8af6719.ngrok.io/?identity=tom&room=tombob")
7. I then used the ngrok url with the identity and the room as the tokenurl in the quickstart view controller as follows
 
             var tokenUrl = "https://b8af6719.ngrok.io/?identity=tom&room=tombob"

8. I ensured the value of the access token was "TWILIO_ACCESS_TOKEN" and run the code in the simulator. 
9. I used the same tokenUrl but with a different identity and run the code on my iPhone

            var tokenUrl = "https://b8af6719.ngrok.io/?identity=bob&room=tombob"

10. I logged into both devices and got an error

#### Code

```swift
// This is the only part of the code that was edited for the remote access token
    var accessToken = "TWILIO_ACCESS_TOKEN"
    var tokenUrl = "https://b8af6719.ngrok.io/?identity=tom&room=tombob"
```

#### Expected Behavior

I expected the code to create a room called "tombob" in Twilio, to generate access tokens for users "tom" and "bob" and to allow the two users to enter the chat room. 

#### Actual Behavior

When I tried to log in as tom and bob in the simulator and the iPhone device, I got an error saying "Missing authorization token". I also got an error saying SSL_ERROR_ZERO_RETURN(6) 

#### Reproduces How Often

100%

#### Logs

```
SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert
error is Error Domain=com.twilio.video Code=31102 "Missing authorization token" UserInfo={NSLocalizedDescription=Missing authorization token}
```

### Versions

I don't know the version number but I downloaded it from github on 22nd March 2018

#### Video iOS SDK

Twilio Video 2.0.0-beta3

#### Xcode

9.2

#### iOS Version

11.2 and 10.3.3

#### iOS Device

iPhone 5S

**Comment by paynerc** [comment]
Hello there,

Sorry for the long response time as I was out for the holiday weekend. Were you able to validate that the server you were running was indeed returning a token to the application? i.e. did you set a breakpoint and validate that it returned a JWT token?

Also, can you attach the link to the code that you are using for the Video Access Token Server? I would like to make sure that I am setting up the same testing environment to work through this.

Thanks!

Ryan

**Comment by paynerc** [comment]
@EricMwangi,

Just checking in to see if you have resolved this issue or if there is omitting that we can do to further assist you?

Thanks,

Ryan

**Comment by paynerc** [comment]
@EricMwangi,

I am assuming that you have resolved this issue at this point? Please feel free to reopen this issue if you are still having issues.

Ryan

**Comment by mudi256** [comment]
i'm facing this issue in android java
