### ISSUE TITLE
how to add track after room join successfully in iOS ?

### ISSUE THREAD

**Issue by kushJadia** [twilio/video-quickstart-swift#256]

**Comment by piyushtank** [comment]
@kushJadia Can you provide the Video SDK version you are using? 

In 2.0, once you are connected to a Room, you can publish (i.e. add) track using the following APIs - 

```
[room.localParticipant publishAudioTrack:localAudioTrack]
[room.localParticipant publishVideoTrack:localVideoTrack]
[room.localParticipant publishDataTrack:localDataTrack]
```

**Comment by piyushtank** [comment]
@kushJadia you were able to publish tracks in your app. Feel free to reach out if you have any questions.

**Comment by kushJadia** [comment]
@piyushtank thanks for your help.
