### ISSUE TITLE
Build Error: Use of undeclared type "TVIDefaultAudioDevice"

### ISSUE THREAD

**Issue by Sachin0912** [twilio/video-quickstart-swift#259]
Please check this screenshot , I am getting this error on my project and demo Quickstart project as well, please reply asap. 

Thanks in advance.

![screen shot 2018-04-30 at 3 02 23 pm](https://user-images.githubusercontent.com/17583565/39421849-95ef9ecc-4c88-11e8-8951-405a865bd0c9.png)

**Comment by paynerc** [comment]
@Sachin0912,

Any update on this issue? Have you resolved things?

Thanks!

Ryan

**Comment by ceaglest** [comment]
Hi,

Please re-open this ticket if you're still having problems installing the Framework.

Thanks,
Chris
