### ISSUE TITLE
TVIRemoteDataTrackDelegate not catching .send

### ISSUE THREAD

**Issue by nah2015** [twilio/video-quickstart-swift#262]
### Description

I have TVILocalDataTrack() set up as described here https://www.twilio.com/docs/video/ios-v2-using-the-datatrack-api

Trying to send a simple string over DataTrack API

Upon entering the video session, each user receives "Subscribed to data track" log message from TVIRemoteParticipantDelegate - but `extension TwilioVideoViewController : TVIRemoteDataTrackDelegate` doesnt seem to be working.  I have a print within it, and it is never executed.

I have my send() function with my data inside of func subscribed() and I print information within that function - which all gets executed correctly - but like I said, it doesn't seem to be caught by TVIRemoteTrackDelegate

See my code:

#### Code

Initialize within my ViewController
`var localDataTrack = TVILocalDataTrack()`

Add localDataTrack to builder inside connect function
`@IBAction func connect(sender: AnyObject) {
        
        if (accessToken == "TWILIO_ACCESS_TOKEN") {
            let SWSuserName = "\(tokenUrl)\(nameTextField.text!)&room=\(roomTextField.text!)"
            do {
                accessToken = try TokenUtils.fetchToken(url: SWSuserName)
            } catch {
                let message = "Failed to fetch access token"
                logMessage(messageText: message)
                return
            }
        }
        
        // Prepare local media which we will share with Room Participants.
        self.prepareLocalMedia()
        
        // Preparing the connect options with the access token that we fetched (or hardcoded).
        let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [TVILocalAudioTrack]()
            builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : [TVILocalVideoTrack]()
            
            // The name of the Room where the Client will attempt to connect to. Please note that if you pass an empty
            // Room `name`, the Client will create one for you. You can get the name or sid from any connected Room.
            builder.roomName = self.roomTextField.text
            
            if let localDataTrack = self.localDataTrack {
                builder.dataTracks = [localDataTrack]
            }
            
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideo.connect(with: connectOptions, delegate: self)
        
        logMessage(messageText: "Attempting to connect - \(String(describing: self.roomTextField.text!))")
        
        self.showRoomUI(inRoom: true)
        self.dismissKeyboard()
    }`

extension TVIRoomDelegate, inside didConnect() function
`if let localParticipant = room.localParticipant,
            let localDataTrack = self.localDataTrack {
            localParticipant.publishDataTrack(localDataTrack)
        }`

Send function
`func send() {
        if techniciansArray.contains(swsUser) {
            let message = ticketNumber
            print("user is a technician so we arent sending ticketnumber variable")
            //since user isnt a technician, they are sending a message (which is ticket number)
        } else {
            let message = ticketNumber
            localDataTrack?.send(message)
            print("user is a customer so we send \(message) to the technician for post session reporting")
        }
    }`

extension TVIRemoteParticipantDelgate - inside of subscribed(to audioTrack) function
`send()`

Remote Data Track Delegate extension
`// MARK: TVIRemoteDataTrackDelegate
extension TwilioVideoViewController : TVIRemoteDataTrackDelegate {
    
    func remoteDataTrack(_ remoteDataTrack: TVIRemoteDataTrack, didReceive message: String) {
        print("remoteDataTrack:didReceiveString: \(message)")
        
        if techniciansArray.contains(swsUser) {
        let technicianTicketNumber = message
            ticketNumber = technicianTicketNumber
            print("we receive ticket number \(ticketNumber) from user to technicians ticket number variable so they can go to the feedback page post session")
        } else {
            print("we leave ticket number as is since user is not technician")
        }
        
    }

}`

#### Expected Behavior

Expecting to see "remoteDataTrack:didReceiveString:" somewhere in console but never do

### Versions

All relevant version information for the issue.

#### Video iOS SDK

2.0.0 via CocoaPods

#### Xcode

Current

#### iOS Version

Current

#### iOS Device

Simulator and iPhone 7+

Any insight at all would be greatly appreciated!

**Comment by paynerc** [comment]
Good morning!

Looking at your description, one thing I don't see you mentioning is that you are setting the delegate on the remote data track? When you receive the `func subscribed(to dataTrack: TVIRemoteDataTrack, publication: TVIRemoteDataTrackPublication, for participant: TVIRemoteParticipant)` callback, you would then want to set the delegate on the `TVIRemoteDataTrack` object so you will receive the `func remoteDataTrack(_ remoteDataTrack: TVIRemoteDataTrack, didReceive message: String)` callback.

If you take a look at the [ViewController.swift](https://github.com/twilio/video-quickstart-swift/blob/master/DataTrackExample/ViewController.swift#L307-L318) from the DataTrackExample, you will see where we are setting the delegate when the remote data track is subscribed.

Let me know if you are setting the delegate on the remote data track during the subscription callback. If you are, we will need to dig a little deeper.

Ryan

**Comment by nah2015** [comment]
Good morning and thank you for the quick response!

My subscribed to datatrack looks like this

`func subscribed(to dataTrack: TVIRemoteDataTrack,
                    publication: TVIRemoteDataTrackPublication,
                    for participant: TVIRemoteParticipant) {
        
        // We are subscribed to the remote Participant's data Track. We will start receiving the
        // remote Participant's data messages now.
        dataTrack.delegate = self
        
        logMessage(messageText: "Subscribed to data track from \(participant.identity)")
    }`


I believe you're referring to `dataTrack.delegate = self` ??

**Comment by nah2015** [comment]
I've figured it out.  Somehow.  I'm not sure what I did that caused it to work because I've been trying a number of things.

One thing I did do was rename my send function to sendmessage() and then I moved the execution of it to subscribed(to dataTrack) function after `dataTrack.delegate = self`

Regardless, it is working as expected now.

Thank you!
