### ISSUE TITLE
CallKit speaker button enabled briefly when defaulting audio to receiver instead of speaker

### ISSUE THREAD

**Issue by jnagel33** [twilio/video-quickstart-swift#265]
### Description

In our app we are using the sdk for voice calls and want to default the audio to receiver instead of speaker. 

So we change the mode so of the default audio device as suggested in the docs:

        ``` self.audioDevice = TVIDefaultAudioDevice(block: {
            kDefaultAVAudioSessionConfigurationBlock()
            
            do {
                try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVoiceChat)
            } catch {
                print(error)
            }
        })
        TwilioVideo.audioDevice = self.audioDevice ```

This works for the most part but there is a strange visual issue when accepting a call through CallKit. The speaker button when first accepting is toggled on and then just before the call connects it toggles off. It looks like the audio route changes from receiver to speaker then back to receiver when the call connects when debugging by observing: `AVAudioSessionRouteChange`. So the unexpected part is that it tries to switch to speaker at all. I thought this might because of the calling of the `kDefaultAVAudioSessionConfigurationBlock()` but that doesn't appear to be the case.

### Steps to Reproduce

1. Change audio device to voice chat instead of video chat
2. Simulate incoming call while on lock screen
3. Tap accept. Notice that speaker button is on initially before toggling off

#### Code

        ``` self.audioDevice = TVIDefaultAudioDevice(block: {
            kDefaultAVAudioSessionConfigurationBlock()
            
            do {
                try AVAudioSession.sharedInstance().setMode(AVAudioSessionModeVoiceChat)
            } catch {
                print(error)
            }
        })
        TwilioVideo.audioDevice = self.audioDevice ```

#### Expected Behavior

If the audio device is setup to play through the receiver instead of the speaker than the speaker button should not be toggled on when accepting.

#### Actual Behavior

Speaker button is toggled on initially before correcting itself

#### Reproduces How Often

Evertime

### Versions

2.0.4

#### Video iOS SDK

2.0.4

#### Xcode

9.3

#### iOS Version

11.3

#### iOS Device

iPhone X

**Comment by piyushtank** [comment]
@jnagel33 Thanks for reaching out. I made changes in our CallKit sample app to simulate the problem. After making changes in the block, the speaker button stays off and audio is correctly routed to receiver.I have commited my changes to my fork  if you want to try it out. [Here](https://github.com/piyushtank/video-quickstart-swift/commit/32bbfbb6884165890eb621e047c4c8727ffd903f) is the commit.

This is how I tried to reproduce the problem on CallKit sample app after changes are made -
1. Press `Simulate incoming call` button.
2. Enter "Room name", press OK. (By default delay in seconds is 5 seconds)
3. Lock the phone.
4. Incoming call will be simulated in 5 seconds. Answer the call.
5. Speaker button stays off and bi-directional audio works as expected.

[Here](https://github.com/piyushtank/video-quickstart-swift/tree/callkit-ui-speaker) is the branch with change.

Let me know if you have any questions.

**Comment by jnagel33** [comment]
@piyushtank Thanks for looking at the issue. I pulled your branch and tested again and unfortunately I'm still seeing the same issue on my device. The speaker button is disabled by the time the call connects but it is enabled initially for some reason.

**Comment by jnagel33** [comment]
@piyushtank Interesting. I am seeing the speaker enabled initially when the ringer is on for both SpeakerBox and the Quickstart app. 

When the ringer is off, I am still seeing the behavior on the Quickstart app and I am not able to reproduce on SpeakerBox. So I guess that is the only remaining difference for me.

**Comment by piyushtank** [comment]
@jnagel33 When ringtone is ON, my observation is, the speaker button stays ON in the connecting state and once the call gets connected, the speaker button switches to OFF - both on SpeakerBox and Quickstart. This is apparent in QuickStart because it sends a connect request to server to connect to a Room and waits for the connect success response.

Let me know if you have any questions.

**Comment by jnagel33** [comment]
So you're right about the speaker button being on when the ringtone is on. That appears to be how iOS handles the transition. 

The regression that I'm seeing is that when ringtone is OFF - the speaker button is still enabled initially on the quickstart app. I can't reproduce this when using TwilioVideo 1.0 or on the SpeakerBox app.

**Comment by piyushtank** [comment]
@jnagel33 Thanks! I will try to reproduce and get back soon.

**Comment by jnagel33** [comment]
@piyushtank Thanks for spending time to debug this one with me. You're right, if I don't fulfill the answer call action immediately on Speakerbox then I see the speaker button enabled. So this is definitely something that occurs on their end and is not something caused by the SDK. I will close this issue out.

**Comment by piyushtank** [comment]
Thanks @jnagel33 
Let us know if you run into any issue while using the video SDK.
