### ISSUE TITLE
twillo video sdk not working in swift 

### ISSUE THREAD

**Issue by somsin** [twilio/video-quickstart-swift#27]
iOS/Pods/TwilioCommon/TwilioCommon.framework/TwilioCommon, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/somendra/Documents/iOS/Pods/TwilioCommon/TwilioCommon.framework/TwilioCommon

iOS/Pods/TwilioConversationsClient/TwilioConversationsClient.framework/TwilioConversationsClient, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/somendra/Documents/iOS/Pods/TwilioConversationsClient/TwilioConversationsClient.framework/TwilioConversationsClient

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TWCCameraCapturer", referenced from:
      type metadata accessor for __ObjC.TWCCameraCapturer in TwilioManager.o
  "_OBJC_CLASS_$_TWCConversation", referenced from:
      type metadata accessor for __ObjC.TWCConversation in TwilioManager.o
  "_OBJC_CLASS_$_TWCIncomingInvite", referenced from:
      type metadata accessor for __ObjC.TWCIncomingInvite in TwilioManager.o
  "_OBJC_CLASS_$_TWCLocalMedia", referenced from:
      type metadata accessor for __ObjC.TWCLocalMedia in TwilioManager.o
  "_OBJC_CLASS_$_TWCOutgoingInvite", referenced from:
      type metadata accessor for __ObjC.TWCOutgoingInvite in TwilioManager.o
  "_OBJC_CLASS_$_TwilioAccessManager", referenced from:
      type metadata accessor for __ObjC.TwilioAccessManager in TwilioManager.o
  "_OBJC_CLASS_$_TwilioConversationsClient", referenced from:
      type metadata accessor for __ObjC.TwilioConversationsClient in TwilioManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[http://stackoverflow.com/questions/38642693/twillo-video-sdk-not-working](

**Comment by JRG-Developer** [comment]
Are you using Xcode 8.0? Based on these errors, I suspect you are. ;)

Have you tried using the latest, release-candidate version of CocoaPods? I'm using CocoaPods v. 1.1.0.rc.2, and I'm able to build and run just fine. :)

You can install this via `sudo gem install cocoapods --pre`.

You should then confirm your CocoaPod version via `pod --version`.

If it shows a previous version instead, an easy workaround is to simply uninstall the others via `sudo gem uninstall cocoapods`.

You can also try trashing your `pods` directory and `.workspace` file, and doing `pod install` again. I've seen goofy things happen with pod install, and this helps sometimes too.

**Comment by idelgado** [comment]
@JRG-Developer thanks for providing feedback on this issue.

Closing this since it is likely resolved at this point.
