### ISSUE TITLE
Remote video feed does not render

### ISSUE THREAD

**Issue by nfasate** [twilio/video-quickstart-swift#270]
### Description

Hello,

We used programmable video iOS SDK (version: 1.3.7) for the multiparty video call. The problem is whenever we do a multiparty video call, the call gets connected and sound transmitted well but remote video feed does not render on remote view.

We debug the code to see whats wrong, we found that no delegate method of the 'TVIRoomDelegate' is getting called. Also, we check Twilio VideoQuickStart (version: 'TwilioVideo', '~> 1.4') demo app but the same result.

We facing this issue from yesterday only, before it was worked properly.

#### Expected Behavior

Remote video feed should render on remote view.

#### Actual Behavior

Remote video feed does not render on remote view.

#### Reproduces How Often

The issue occurs with every video call that we have raised.

#### Logs

```
Please find logs from below URL:
(https://docs.google.com/document/d/1fO6f42Qyyl7eyZ_nDOqcp7KwS5MxwaxchTCCvEUy77k/edit?usp=sharing)
```

### Versions

'TwilioVideo', '~> 1.4'

#### Video iOS SDK

1.4 via CocoaPods

**Comment by nfasate** [comment]
Actually, we have set video codec H.264 on our programmable video console setting, and we used iOS 1.x SDK, that only supports VP8 (and VP9). So we changed codec H.264 to VP8 & H.264 and it's working.

**Comment by paynerc** [comment]
Good morning @nfasate,

Investigating this ticket was the first thing on my agenda for this morning and I see that you already resolved it. Yes, the `1.x` version of the SDK doesn't support H.264. The `2.x` releases have been GA'd a few weeks ago and offer this support. Is there a reason why you haven't investigated moving to the latest release? We won't be adding any new features to the `1.x` version, so I would suggest at least trying out the `2.x` version so you can benefit from any new features and bug fixes that we release.

If you have any further questions, please don't hesitate to reach out.

Ryan
