### ISSUE TITLE
TwilioConversations is not working in ios .

### ISSUE THREAD

**Issue by somsin** [twilio/video-quickstart-swift#28]
I am trying to make a call from my android client to ios client  then i am geting this error at the ios 
"
[ERROR:TwilioConversations:[Signaling]:RESIP::TRANSPORT: Got TLS read ret=0 error=6 error:00000006:invalid library (0):OPENSSL_internal:public key routines](url)
"
client side but when i am doing android client  to android client call is working fine  

Not able to get where is the issue

**Comment by ykhodosh** [comment]
Hi,

I have a few questions to try narrowing down the problem:

1) What are the versions of Twilio Conversations SDK for Android and iOS you are using?
2) Can you please enable debug logging in both clients and capture the entire log on both sides, including the client initialization part where it attempts to `listen` for the calls.
3) Are you using any third party libraries in you app, such as OpenSSL, POCO?

**Comment by csersurya** [comment]
Hi,

I am also in a similar situation, similar error in case of IOS, i am using TwilioConversationsClient 0.25.0. 

Please help.

**Comment by idelgado** [comment]
@somsin @csersurya please give our new Video library a try. We've solved a lot of problems related to initiating a call by allowing developers to connect to named rooms instead.

https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk
