### ISSUE TITLE
Using REST API to complete a room, iOS SDK does not provide an Error/Reason in roomDidDisconnect

### ISSUE THREAD

**Issue by andschdk** [twilio/video-quickstart-swift#281]
### Description
While trying to distinguish between a user initiated "disconnect" and a "remote" (i.e. server completing the room) I read this in the docs:

`- (void)room:(nonnull TVIRoom *)room didDisconnectWithError:(nullable NSError *)error;`
> This method is invoked when the Client disconnects from a Room.
>
> param **room** The Room from which the Client disconnected.
> param **error** An NSError describing why disconnect occurred, **or nil if the disconnect was initiated locally.**

That lead to using the `error` to determine one case or the other. However this is not the actual behaviour. When a room is completed from the server using the REST API (or in my case the python lib) the iOS SDK is invoking the method with `error=nil`.

### Steps to Reproduce

1. Connect to room
2. Complete room using REST API
3. Delegate method is invoked with no error

#### Expected Behavior
An NSError describing why disconnect occurred is expected.

#### Actual Behavior
No error in callback, looks like a local initiated disconnect

#### Reproduces How Often
100%

### Versions
2.2.0

### Related
#251 

Thanks.

**Comment by ceaglest** [comment]
Hey @andschdk,

Thanks for filing an issue.

> That lead to using the error to determine one case or the other. However this is not the actual behaviour. When a room is completed from the server using the REST API (or in my case the python lib) the iOS SDK is invoking the method with error=nil.

I agree that this is incorrect behavior. You should receive some indication that a Room was completed, and right now it is in distinguishable from a local initiated disconnect. We've heard the same feedback from a few Javascript customers and have spec'd out a signaling event and codes to cover this scenario.

I'll double check where we are on rolling this out, and get back to you next week.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @andschdk,

We are now testing changes to our signaling service to make this use case distinguishable. However, we will need to make a small update to our Clients in order to surface the completed Room state. We have cut an internal ticket CSDK-2453 to track the work for our mobile SDKs.

It is likely that this change will land in twilio-video.js first, and then mobile Clients after. If you are interested, there is more discussion of this behavior in: https://github.com/twilio/twilio-video.js/issues/255.

Best,
Chris

**Comment by andschdk** [comment]
Thanks for the update, looking forward 👍

**Comment by ceaglest** [comment]
Hi @andschdk,

The Server side changes are now deployed in production and I've implemented support in our C++ Client to raise the error. I've also released the updated C++ client to our internal teams, and we expect to consume it in our upcoming 2.3.1 iOS release.

It will likely be a couple of weeks before 2.3.1 is out, but it should give you what you're looking for.

Best,
Chris

**Comment by ceaglest** [comment]
Hey @andschdk,

I was out on vacation when this landed, but [2.4.0](
https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#240-august-28-2018) includes room completion errors. Please give it a shot if you haven't picked it up already.

Thanks,
Chris

**Comment by andschdk** [comment]
Hi @ceaglest,
Thank you for letting me know. I have not worked on this lately, had to put it aside for a while. I should be ready to catch up again at the end of this month hopefully.

Looking forward trying this out. 👏

**Comment by andschdk** [comment]
Hi @ceaglest,
Sorry for the delay. 

I just checked this and can confirm that this now works. Thanks. 👍
