### ISSUE TITLE
20154 Invalid Token claims set Twillio Video  

### ISSUE THREAD

**Issue by mrchauhan2802** [twilio/video-quickstart-swift#305]
SIP/2.0 403 Forbidden

Call-ID: Gw0M0cxXF2tIQs3yMYWi2g..

CSeq: 1 INVITE

Server: Twilio

X-Twilio-Error: **20154 Invalid Token claims set**

X-Twilio-LegInfo: external

X-Twilio-TlsVerify: true

is that server problem or in iOS problem ??
What is solution ?

**Comment by paynerc** [comment]
@mrchauhan2802,

Without seeing your token, my assumption is that there is something not being set properly when you are generating the token on your server.

If you wouldn't mind, send an email to support@twilio.com, reference this GitHub issue and include a generated token and I will take a look. Also post a comment here when you send the email and I will check in the support system for the issue.

Thanks!

Ryan

**Comment by mrchauhan2802** [comment]
Yes issue solved

**Comment by paynerc** [comment]
Awesome. Let us know if you run into anything else.

**Comment by suhaskurade8** [comment]
@paynerc  @mrchauhan2802 Can u share the details how do u solve the issue?
