### ISSUE TITLE
Incoming Video Call

### ISSUE THREAD

**Issue by Hamza123Imran** [twilio/video-quickstart-swift#306]
Hi, i have implemented video call in my ios app. I have generated my own token with php backend server. Now i want to confirm things, that how can we know about incoming video call, Like on skype it shows us notification type for incoming call? Suppose if user A calls B and user B app is in background mode then how can user B be notify about incoming video call?

**Comment by paynerc** [comment]
Good morning @Hamza123Imran,

`TwilioVideo` supports the concept of room, where the participants join a room. There is no inherent notion of a call.

You can use push notifications, or [Twilio Notify](https://www.twilio.com/notify) as a mechanism to signal to individuals that there is a room waiting for them to join. This can even be tied into CallKit on iOS 10 and above and gives you the "incoming call" feel. You can see the CallKit QuickStart in this project that shows how to interact with the CallKit APIs to give the appearance of an "incoming call". All you would need to do in a production app is use a method for notifications as I described above.

If you have any further questions, please let us know.

Ryan

**Comment by Hamza123Imran** [comment]
Is Twilio Notify work for iOS App also? and secondly if i'm having peer to peer video call than both parties should have same room name?

**Comment by paynerc** [comment]
Yes, Twilio Notify works with iOS. Take a look at the [Notify iOS Quickstart documentation](https://www.twilio.com/docs/notify/quickstart/ios) for further information.

Yes, both parties will need to join the same room name. Each participant will be required to have a unique identity, but the room name should be the same. 

Ryan

**Comment by paynerc** [comment]
I'm hoping that you have found what you needed with regard to notifying participants about going a call. I am going to close this issue, but feel free to reach out if you have any further questions.

Ryan

**Comment by Hamza123Imran** [comment]
Yup, i have done this through firebase push notification . Thanks for your guidance
