### ISSUE TITLE
related to incoming call using call kit

### ISSUE THREAD

**Issue by VDPurohit** [twilio/video-quickstart-swift#318]
Hello there,

I was implementing text,audio and video chat so is it possible to we can use same voIP certificate which generated from "developer.apple.com" for audio as well as video?

For demo I used this link:-https://github.com/twilio/video-quickstart-swift
I already refer this link :- https://github.com/twilio/video-quickstart-swift/issues/234

Thank you

**Comment by paynerc** [comment]
Yes, using that same certificate should work. You would need to manage sending the push notifications using some mechanism, such as [Twilio Notify](https://www.twilio.com/notify). In that notification you could provide payload information that alerts your app whether its a voice only or video call and your app could then respond as required.

Ryan

**Comment by VDPurohit** [comment]
@paynerc thanks for response I got it.
👍

**Comment by VDPurohit** [comment]
@paynerc I have some question like:-
1. can twilio provides a trigger until participant didn't;t join or we use "TVIRoomDelegate" for this? 
2.can we have chat option available during audio as well video call?
3.Is twilio provide call logs?
4.can we start recording during call or when we stared from?

Thanks

**Comment by paynerc** [comment]
I see you have moved your questions to #320. I will answer them there and closing this issue.
