### ISSUE TITLE
related logs and other features

### ISSUE THREAD

**Issue by VDPurohit** [twilio/video-quickstart-swift#320]
I have some question like:-

1.Can twilio provides a trigger until participant didn't join or we use "TVIRoomDelegate" for this?
2.Can we have chat option available during audio as well video call (one to one and Group chat)?
3.Is twilio provide call logs?
4.Can we start recording during call or when we stared from?
5.Can we join user anonymously as observer without participant?

please attached link for iOS app
Thanks

**Comment by paynerc** [comment]
In response to your questions:

> 1.Can twilio provides a trigger until participant didn't;t join or we use "TVIRoomDelegate" for this?

The `func room(_ room: TVIRoom, participantDidConnect participant: TVIRemoteParticipant)` delegate method is called when remote participants join the room. From your question, it appears that you are looking for a notification that a remote participant did **not** join the room? Am I reading that correctly?

> 2.Can we have chat option available during audio as well video call (one to one and Group chat)?

You should be able to use Twilio [Programmable Chat](https://www.twilio.com/chat) alongside the `TwilioVideo.framework` in your application.

> 3.Is twilio provide call logs?

Yes, you can access the Room Logs from your Twilio account by heading to the following page: https://www.twilio.com/console/video/logs/rooms/

> 4.Can we start recording during call or when we stared from?

There is currently no iOS API to turn on recording during a call. You can do a couple things to enable recoding when a room is created, however. The first is to enable recordings for all rooms. This is done in the Twilio Console from the [Room Settings](https://www.twilio.com/console/video/configure) page. In the *Default Settings* section you can specify that `Recording` is enabled. Therefore all rooms will have recordings enabled when participants join the room. The other thing you can do is create the room via the REST API and set the `RecordParticipantsOnConnect` parameter to `true`. Using this method you could decide when creating specific rooms that you want it to be recorded. You can see the [REST API documentation](https://www.twilio.com/docs/video/api/recordings-resource) for further information. An important note is that recordings are only supported for `Group` rooms.

> 5.Can we join user anonymously as observer without participant?

All connections to the room will cause a participant to be added to the room. To act as an observer, the joining participant just wouldn't share their local audio and video tracks. This would allow the observing participant to receive the other audio and video tracks without publishing any of their own tracks.

I hope this answers your questions. Let us know if you have any further questions.

Ryan

**Comment by VDPurohit** [comment]
@paynerc 
Thanks for response I got your points and first is exactly what I m looking for?

3.Is twilio provide call logs?
Yes, you can access the Room Logs from your Twilio account by heading to the following page: https://www.twilio.com/console/video/logs/rooms/

So can we saw in my iOS app?

**Comment by VDPurohit** [comment]
@paynerc 
Any update?

**Comment by VDPurohit** [comment]
@paynerc  please close it.
