### ISSUE TITLE
Related to feedback and rate

### ISSUE THREAD

**Issue by VDPurohit** [twilio/video-quickstart-swift#321]
1.Can we rate and feedback on call on my app?
After research I got this link:-https://www.twilio.com/docs/voice/api/call-quality-feedback ,So what I need to implement in my iOS app or I just passed rate and feed back only on that php(suppose for setup)file and what for retrieving?

2.Can we have chat option available during audio as well video call (one to one and Group chat)?
-So, We can use programmable chat and Video SDK side by side right?

3.Is twilio provide call logs?
Yes, you can access the Room Logs from your Twilio account by heading to the following page: https://www.twilio.com/console/video/logs/rooms/
-So can we saw in my iOS app or we store in my local server DB?

4.Can we start recording during call or when we stared from?
Using Rest API I need to just call that php page(Suppose we setup with php) with SID and token right?which sep required for retire that recording by the client?

Thanks

**Comment by ceaglest** [comment]
Hi @VDPurohit,

> 1.Can we rate and feedback on call on my app?
After research I got this link:-https://www.twilio.com/docs/voice/api/call-quality-feedback ,So what I need to implement in my iOS app or I just passed rate and feed back only on that php(suppose for setup)file and what for retrieving?

That document is for the Voice SDKs. We don't currently have a feedback API for the Video SDKs, but we may add something along these lines in the future.

> 2.Can we have chat option available during audio as well video call (one to one and Group chat)?
-So, We can use programmable chat and Video SDK side by side right?

Yes, you can use our Programmable Chat SDK alongside Video if you need things like persistence of chat messages, and channels outside of the context of a Room. If the content is ephemeral, and scoped to the Room you could consider using the [DataTrack](https://www.twilio.com/docs/video/ios-v2-using-the-datatrack-api) APIs offered in our Video SDKs to broadcast messages.

> 3.Is twilio provide call logs?
Yes, you can access the Room Logs from your Twilio account by heading to the following page: https://www.twilio.com/console/video/logs/rooms/
-So can we saw in my iOS app or we store in my local server DB?

Yes, you can also control logging on the Client side using [TwilioVideo.logLevel](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TwilioVideo.html#//api/name/setLogLevel:). We use NSLog internally, but you can redirect the entire log output to a file if you wish.

> 4.Can we start recording during call or when we stared from?
Using Rest API I need to just call that php page(Suppose we setup with php) with SID and token right?which sep required for retire that recording by the client?

You can't start/stop recording after a Room is created, but you can control recording on a per-Room basis (when using the REST API to create Rooms). You can also set account level defaults which apply to ad-hoc Rooms in the [console](https://www.twilio.com/console/video/configure). If you want to learn more about the REST API, including PHP examples see:

https://www.twilio.com/docs/video/api/rooms-resource#post-list-resource
https://www.twilio.com/docs/video/api/recordings-resource

Please let me know if you have any more questions.

Regards,
Chris

**Comment by ceaglest** [comment]
Hello,

Please let us know if you need any more help with Video in the future.

Thanks,
Chris
