### ISSUE TITLE
Participant disconnected because of duplicate identity?

### ISSUE THREAD

**Issue by keval94** [twilio/video-quickstart-swift#330]

**Comment by paynerc** [comment]
@keval94,

Each participant that connects to the room requires a separate identity. This is backed into the access token that you provide when connecting to a room.

For further information, please take a look at these documents regarding access tokens:

* https://www.twilio.com/docs/video/ios-v1-getting-started#3-generate-an-access-token
* https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens

Please let me know if you have any further questions.

Ryan

**Comment by paynerc** [comment]
@keval94,

I am going to close this issue out. If you have any further issues, feel free to re-open it.

Ryan

**Comment by Mu-Aleem** [comment]
hello everyone i,m using the twilio-video on react js side . but sometime my Participant video not show and sometime show please help me to solve this issue
