### ISSUE TITLE
TVIRoom number of remote participants is always 0

### ISSUE THREAD

**Issue by wassimseif** [twilio/video-quickstart-swift#332]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

[Description of the issue]

### Steps to Reproduce

1. User 1 connects to RoomA
2. User 2 connects to RoomA
3. participantDidConnect not called

#### Code

```swift
let connectOptions = TVIConnectOptions.init(token: payload.twilioAccessToken) { (builder) in
    builder.roomName = payload.roomName
}
twilioLog("Will Connect to room with name \(String(describing: payload.roomName))")


self.room = TwilioVideo.connect(with: connectOptions, delegate:self)```

#### Expected Behavior

participantDidConnect called when the second participants joins
#### Actual Behavior

`participantDidConnect` not called
Even room.remoteParticipants returns 0 


#### Reproduces How Often

100%


### Versions

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]
- TwilioVideo (2.5.3) Cocoapods
#### Xcode

10.1

#### iOS Version
12.1


#### iOS Device

iPhone X,
iPhone 6S

**Comment by ceaglest** [comment]
Hi @wassimseif,

This is a pretty fundamental feature of our Video platform which should work as you describe. 

First, you should double check that User 1 and User 2 both `didConnectToRoom:` events.

Second, note that the identity of each Participant must be unique (recently asked, see https://github.com/twilio/video-quickstart-swift/issues/330), so you should double check that each user gets a token with a unique identity. 

If you are not using unique identities, then when User 2 joins, User 1 will be disconnected due to a duplicate identity error.

Regards,
Chris

**Comment by wassimseif** [comment]
Hey,
Thanks for the reply. Yes I do understand that this is one of the main features of Twilio Video & most probably I'm doing something wrong.

To double check, this is exactly the flow I'm doing  : 

1. The backend generates a room Id & creates the room using your REST API
2. The backend generates 2 Acces tokens ( using your REST APIs) & add Video Grants to these tokens
3. User A gets one of the unique tokens & the generated room ID ( question: Do i connect to room using the room name I generated OR the `sid` I got back from your create room REST API ?)
4. User A connects to the room & the `didConnectToRoom` is called
5. After a delay of 10 secs, User B gets the other access token & the generated room name
6. User B connects to room & the `didConnectToRoom` is called

What I think should happen is that the `room:participantDidConnect:` delegate implemented on User A should be called notifying him that User B connected to the room, however, it's not called 
Also .After a sometime ( 1-2min ) I launch the debugger on User A & print out the number of `remoteParticipants` in the room but it's always 0.

**Comment by MakwanaRohit** [comment]
Hey I'm facing same issue please help me

**Comment by wassimseif** [comment]
Hey @MakwanaRohit ,
I got my problem solved. The issue was that when creating the `AccessToken` from Twilio. You have to send a unique identifier for each token. We were sending a static string.

**Comment by ceaglest** [comment]
Awesome, thats great to hear @wassimseif!

@MakwanaRohit you probably do have the same issue. Please do check what access token you are providing, and that it is valid for each Participant.

**Comment by ceaglest** [comment]
Closing, since the original request was resolved. @MakwanaRohit, please reopen if you are still having token issues.
