### ISSUE TITLE
How can i Chnage Loud Speaker to Normal in Swift ? 

### ISSUE THREAD

**Issue by keval94** [twilio/video-quickstart-swift#333]

**Comment by MakwanaRohit** [comment]
Hi Please try below code        

self.isSpeakerON = !self.isSpeakerON //Manage Bool Variable
        
        let session = AVAudioSession.sharedInstance()
        var _: Error?
        try? session.setCategory(AVAudioSessionCategoryPlayAndRecord)
        try? session.setMode(AVAudioSessionModeVoiceChat)
        if self.isSpeakerON {
            try? session.overrideOutputAudioPort(AVAudioSessionPortOverride.speaker)
        } else {
            try? session.overrideOutputAudioPort(AVAudioSessionPortOverride.none)
        }
        try? session.setActive(true)

**Comment by ceaglest** [comment]
Hi @keval94,

Sorry for the delayed response.

Normally, we would play audio on the loudspeaker. If you want to use the iPhone's receiver instead, you can select `AVAudioSessionModeVoiceChat`. Here is a Swift [example](
https://www.twilio.com/docs/video/ios-v2-configuring-audio-video-inputs-and-outputs#selecting-specific-audio-routes) from our guide.

Regards,
Chris

**Comment by ceaglest** [comment]
Let us know if you need any more help on this. Closing since the original question was answered.
