### ISSUE TITLE
When on the video call through CallKit, an incoming call to the iPhone cell number will end the call.

### ISSUE THREAD

**Issue by jocelynlih** [twilio/video-quickstart-swift#336]
### Description

When on the video call through CallKit, an incoming call to the iPhone cell will end the call.

### Steps to Reproduce

1. Caller A and Caller B are on the video call through CallKit.
2. Caller A receives an incoming call to cell number.
3. Caller B noticed the call ends without any notice.

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

Some VoIP call providers are providing the call status update to let caller know that the current call ended because of another call, is that something possible through Video SDK? 

#### Actual Behavior

Call ends without a reason.

#### Reproduces How Often

100%

#### Logs

```
// Log output when the issue occurs
```

### Versions
2.5.*

#### Video iOS SDK

2.5.* from cocoapods

#### Xcode

Xcode 10

#### iOS Version

iOS 12

#### iOS Device

iPhone

**Comment by ceaglest** [comment]
Hi @jocelynlih,

Thanks for writing in. 

> When on the video call through CallKit, an incoming call to the iPhone cell will end the call.

My first question is, how are you testing CallKit support with our 2.5.x SDK? Do you have some code that you could share, which indicates how you are handling CXActions? Or are you using our CallKit [example](https://github.com/twilio/video-quickstart-swift/tree/2.6.0-preview/VideoCallKitQuickStart) instead?

> Some VoIP call providers are providing the call status update to let caller know that the current call ended because of another call, is that something possible through Video SDK?

Yes, as long as you hook into the appropriate CallKit events. See how we handle ended actions [here](https://github.com/twilio/video-quickstart-swift/blob/2.6.0-preview/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L92). And hold actions [here](https://github.com/twilio/video-quickstart-swift/blob/2.6.0-preview/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L110).

Let me know how I can help further.

Thanks,
Chris

**Comment by jocelynlih** [comment]
Hi @ceaglest thx for the quick response. 
To answer your question, yes, we do use similar code for CallKit handling, I will post relevant code soon. 
The problem is when caller A received a phone call on cell, the caller B won’t know this event through CallKit handling, when the call ends, we would like to notice Caller B that the call was ended because of an incoming call.

**Comment by ceaglest** [comment]
Hi @jocelynlih,

Sorry that I misunderstood your question. We don't offer a disconnect reason, or some way to indicate this case at the product level. We do have Data Tracks, which you could use to signal this case to the other Participant.

Consider this flow of events.

1. Callers A, B publish a Data Track, along with their Audio and Video Tracks.
2. Caller A receives phone call.
3. Caller A chooses to end the Twilio Video "call" via CallKit.
4. Caller A sends a message on the Data Track.
5. Caller B responds to the message, indicating receipt ("ack").
6. Caller A receive "ack" from B.
7. Caller A and B disconnect from the Room.

It would be a bit of work to orchestrate this extra signaling, but it would give you the context you need in this case.

https://github.com/twilio/video-quickstart-swift/tree/master/DataTrackExample

Regards,
Chris

**Comment by ceaglest** [comment]
Hi,

Let us know if you need any more help with Video in the future.

Thanks,
Chris

**Comment by mehulparmar4ever** [comment]
Hello Twilio Team,

Any updates on this task?

**Comment by ceaglest** [comment]
Please file a new issue if you need help @mehulparmar4ever.
