### ISSUE TITLE
"Mute" in VideoCallKitQuickstart app doesn't reflect in CallKit UI

### ISSUE THREAD

**Issue by rwbayer** [twilio/video-quickstart-swift#351]
Hello! I'm wondering if there's any way to update CallKit's Mute state when the app's "Mute" button is used. Currently, if you use the CallKit quickstart, the mute button in the app does not affect CallKit's state. Is there anyway to have the app's mute button update the CallKit UI?

### Description

When tapping mute in the quickstart app, and then navigating over to the CallKit UI, the "mute" icon in CallKit is not updated to the appropriate state

### Steps to Reproduce

1. Simulate incoming call & accept
2. Tap mute in app (button will update to display 'unmute')
3. Go to app switcher and slide to the far right to access CallKit UI
4. Mute is not selected. Tapping mute will highlight, but will actually un-mute the app's audio

#### Code

N/A - just using the quickstart code

#### Expected Behavior

I expected the mute button state in the quickstart app to be linked to the mute button state in CallKit

#### Actual Behavior

While adjusting the mute state in CallKit is reflected in the app, adjusting in the app is not reflected in CallKit

#### Reproduces How Often

100%

#### Logs

I don't think it's necessary for this one, but let me know and I can provide some if they'd be helpful.

### Versions

iPhone 6 running 12.1 
iPhone 6 Plus running 12.0.1

**Comment by paynerc** [comment]
@rwbayer,

Sorry for the delayed response on this. You are correct. We were neglecting to update the CallKit system with the mute state when done from the CallKit UI. This was also causing the app UI to be out of sync. I have fixed the issue locally and will be creating a PR momentarily and will link it to this issue. 

Thank you for reporting this issue!

Ryan

**Comment by paynerc** [comment]
@rwbayer,

The PR that fixes this issue has been merged. Grab the latest and let me know if you are seeing any other issues.

Thanks!

Ryan

**Comment by rwbayer** [comment]
Thanks @paynerc - works well! Appreciate the help

**Comment by HighFlyer13** [comment]
@rwbayer thank you for full description! 👍 It helped me in my issue.
