### ISSUE TITLE
Voice and Video in same app, how to handle CXProviderDelegate functions?

### ISSUE THREAD

**Issue by aksthelion** [twilio/video-quickstart-swift#359]
I'm implementing both voice and video in my app. I ran into a situation where CXProviderDelegate are causing issue. How do we handle voice and video in CXProviderDelegate?

E.g.
func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) { 
}
Above is called for both Voice and Video. It's handled differently in voice and video. How do I identify if it's called from voice or video?

**Comment by bchen-twilio** [comment]
Hi @aksthelion 

You should be able to keep a flag if this is a Voice call since the incoming Voice call should be raised from the `callInviteReceived:` delegate method.

By the way, by Video did you mean the Twilio Programmable Video SDK?

Thanks
-bobie

**Comment by paynerc** [comment]
@aksthelion,

When the incoming call comes in and the UUID is assigned, you willed to store some state related to that UUID whether its a voice or video call. And then in the `provider(provider:action:) implementation, you can access the `UUID` property of the `CXAnswerCallAction` object, look up that state you stored previously and then make the determination about whether its Twilio Voice or Twilio Video.

Ryan

**Comment by aksthelion** [comment]
Sorry you again misunderstood this question. I'm not asking how to handle voice and video call same time. I'm asking how to know if an incoming call (only one call at any given time) is a video or voice? Someone suggested following:

**You should be able to keep a flag if this is a Voice call since the incoming Voice call should be raised from the callInviteReceived: delegate method.** 

Is this the best way to handle it?

**Comment by paynerc** [comment]
@aksthelion,

As mentioned in the other ticket, Video doesn't use the same Invite model as Voice does so your notifications of incoming "calls" would be coming through differing pathways. So depending on the pathway, you would be able to determine how to deal with the "call".

Ryan

**Comment by paynerc** [comment]
@aksthelion,

Just checking in to see if you have implemented a solution to this and if we can close out this issue.

Thank you!

Ryan

**Comment by aksthelion** [comment]
I've manage to get it working. Tx
