### ISSUE TITLE
Podfile Correction

### ISSUE THREAD

**Issue by vishalgabani** [twilio/video-quickstart-swift#36]
Hi,

I was trying video-quickstart-swift for Room api. I was trying to add TwilioVideo by "pod install". It was giving error like this,

> [!] Unable to satisfy the following requirements:
> `TwilioVideo (= 1.0-preview1)` required by `Podfile`

So I visited https://github.com/twilio/cocoapod-specs/blob/master/TwilioVideo/1.0.0-preview1/TwilioVideo.podspec - to check the exact version number and it was showing "1.0.0-preview1".

I changed the version in my local podfile and it is working. I am not sure I should use "1.0.0-preview1" version for the demo or not. I just want to make you aware of the error. 

Thanks & Regards,
Vishal Gabani

**Comment by ptankTwilio** [comment]
Hi Vishal,

Thanks for using our Video SDK with Room API and reaching out to us for the problem you are seeing.

I am not able to reproduce the problem you are observing, however I am using cocoapods version 1.0.0-beta.1. I was curious, what version of cocoapods you are running?

Regards,
Piyush Tank

**Comment by vishalgabani** [comment]
Hi Piyush,

Thanks for your reply.

That might be due to my Mac OS Version. I was trying on Yosemite - 10.10.5 with Xcode 7.3 and Cocoapods is 1.0.1. I updated OS to 10.11.6 and Xcode 7.3 to Xcode 8. I forgot checking OS and Xcode requirements.

It is working with El Capitan - 10.11.6, Xcode 8 and Cocoapods 1.0.1.

Thanks & Regards,
Vishal Gabani
