### ISSUE TITLE
How to implement incoming video call alert?

### ISSUE THREAD

**Issue by aksthelion** [twilio/video-quickstart-swift#360]
I'm implemented push notification for incoming video call alert but this is basically a push notification and not a call alert like we have for incoming voice call.

How do we create incoming video call alert which is similar to incoming voice call alert?

**Comment by paynerc** [comment]
@aksthelion 

When you receive the incoming push notification for a video call, you will need to pass that on to the CallKit framework. We have the [CallKit](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart) sample app that shows this. Take a look at the [`reportIncomingCall `](https://github.com/twilio/video-quickstart-swift/blob/master/VideoCallKitQuickStart/ViewController%2BCallKit.swift#L150-L169) method in the `ViewController` `CXProviderDelegate` extension.

Let me know if this helps get you moving in the right direction.

Thanks,

Ryan

**Comment by aksthelion** [comment]
Hello Ryan, My question was not what to do after receiving push notification. My question was about the notification itself. Atm we are sending a PN to other side, I would like to send a call Alert, similar to what we do in voice call, instead of Push Notification. How to alert other side when call is initiated?

**Comment by paynerc** [comment]
@aksthelion,

Voice and Video are very different in that regards. Voice uses the Invite concept, where each client is registered with the Twilio infrastructure and the notifications are handled by Twilio. Video on the other hand doesn't have the inherent concept of invitations. How you notify other participants that you would like them to join a room is left up to the developer to decide. If you are looking to do a similar approach as Voice and "invite" other participants, using APN directly or Twilio [Notify](https://www.twilio.com/notify) is probably the best solution.

Let me know if you have any further questions.

Ryan
