### ISSUE TITLE
Broadcast room feed CDN

### ISSUE THREAD

**Issue by nickoli58** [twilio/video-quickstart-swift#368]
Hi Twilio team!!!

I am wondering about a feature it does not seem is currently available. The use case is there’s a small group of 3 to 4 video participants. Then, users can choose to start a broadcast which is composited and pushed to a CDN for viewing by other noninteractive users in a media player. 

Also, can we have a server join as a participant to do custom recording or pushing to CDN if it’s not filled in as a feature in programmable video?

Thank you!

**Comment by ceaglest** [comment]
Hi @nickoli58,

I'm sorry that we did not respond to your question. 

> Then, users can choose to start a broadcast which is composited and pushed to a CDN for viewing by other noninteractive users in a media player.

You are correct that this isn't a feature that we support today. I can't provide an estimate at the moment, only to say that it is not expected in 1H 2019.

> Also, can we have a server join as a participant to do custom recording or pushing to CDN if it’s not filled in as a feature in programmable video?

Yes, this is indeed possible. Some have had success running a headless node-webrtc Client on the server with twilio-video.js. Others have tried using Client side SDKs (such as [Wowza](https://www.wowza.com)) to broadcast content from a single Participant before its streamed to Twilio.

I haven't tried these personally, but solutions are possible. I can connect you with someone more familiar if you're interested in a server side approach.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

Let us know if you need any more information.

Thanks,
Chris

**Comment by ialexop** [comment]
Hi, @ceaglest I am actually trying to figure out how to do the same thing: set up a room (P2P or group) on Twilio with active participants, and then stream that to potentially thousands of non-active participants (just viewers). Is there an update on what would be the best way to go about it? Thanks!

**Comment by shivarajnaidu** [comment]
Need similar feature.. how to acheive this using twillio group call.. to broadcast group call feed to 1000s of viewers .. is there any quick solution or workaround available ?
