### ISSUE TITLE
ios 12 and Iphone X getting not found front camera and back camera

### ISSUE THREAD

**Issue by lkothapalli** [twilio/video-quickstart-swift#372]
let frontCamera = TVICameraSource.captureDevice(for: .front)
  let backCamera = TVICameraSource.captureDevice(for: .back)

getting nil in ios

**Comment by ceaglest** [comment]
HI @lkothapalli,

Sorry for the late response.

I was wondering, what kind of device are you using, is it an iPhone simulator? Which version of our SDK?

Best,
Chris

**Comment by ceaglest** [comment]
Hi @lkothapalli,

I don't have enough information to reproduce this at the moment. Can you please re-open if you're still experiencing the issue?

Thanks,
Chris
