### ISSUE TITLE
Failed to create provisioning profile. The app ID "com.twilio.ReplayKitExample.BroadcastVideoExtensionSetupUI" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

### ISSUE THREAD

**Issue by neilyoung** [twilio/video-quickstart-swift#377]
Replaykit Example after setting up my dev team. Ideas?

**Comment by neilyoung** [comment]
+ Info
Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the inter-app-audio entitlement.

**Comment by paynerc** [comment]
Good morning!

When you change your development team for the RelayKitExample, you will need to change it for all three targets:
* `ReplayKitExample`
* `BroadcastExtension`
* `BroadcastExtensionSetupUI`

Further, you will need to change the `Bundle Identifier` for each of these targets to a unique name for your development account.

Once you make both of these changes, you should have no further issues code signing and installing the app and extensions on your development device.

Let me know if you have any further questions,

Ryan

**Comment by neilyoung** [comment]
Did this first of course. Did not work. Nevermind. Disregard. Not interested anymore. Thanks

Sent from my iPhone
