### ISSUE TITLE
Crush When Many People Invite Conversation

### ISSUE THREAD

**Issue by bati668** [twilio/video-quickstart-swift#38]
I try to invite 2 people then crush

call 

```
[self.conversationsClient inviteManyToConversation:@[@"PompousCameronXiaoJin",@"FiestyPennyAnchorage"]
                                            localMedia:self.localMedia handler:^(TWCConversation * _Nullable conversation, NSError * _Nullable error) {
        if (conversation != nil) {
            self.conversation = conversation;
            self.conversation.delegate = self;

        } else {
            NSString *errorMessage = [NSString stringWithFormat:@"Error inviting user(%@): %@", identity, [error localizedDescription]];
            [self displayErrorMessage:errorMessage];
            NSLog(@"%@",errorMessage);
        }
    }];
```

then only `FiestyPennyAnchorage` Crush because 
TSCPeerConnection open 
EXC_BAD_ACCESS

or 
MediaStuck EXC_BAD_ACCESS
`PompousCameronXiaoJin` does not crush 

Could you help me??

**Comment by ceaglest** [comment]
@bati668 please give our new Video library a try. We've solved a lot of problems related to initiating a multi-party call by allowing developers to connect to named rooms instead.

https://www.twilio.com/docs/api/video/download-video-sdks#ios-sdk
