### ISSUE TITLE
How to resize TVIVideoView in video call

### ISSUE THREAD

**Issue by rashidabbas** [twilio/video-quickstart-swift#385]
Hi, I am using Twilio in my project for video call and screen sharing but I am facing issue into video call preview View resizing, I want to resize preview view to different height width but when I set height width it applies on view but actual video data remains same height width.

I think there is maintain some aspect ratio in Twilio but I want to change this aspect ratio.
please help me how can I resize video preview height width with custom values.

Thanks in advance.

**Comment by ceaglest** [comment]
Hi @rashidabbas,

> please help me how can I resize video preview height width with custom values.

[TVIVideoView](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIVideoView.html) supports some `UIView.contentMode` settings. For example, if you want to scale the content to fill (by cropping it) you can do the following:

```
myVideoView.contentMode = .scaleAspectFill
```

Just like any other UIView, it's up to you how you size your TVIVIdeoView.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

I hope this answered your question. Feel free to re-open if you're still having content formatting/sizing issues.

Best,
Chris
