### ISSUE TITLE
CallKit video button doesn't bring user to app

### ISSUE THREAD

**Issue by timtraversy** [twilio/video-quickstart-swift#389]
The CallKit Video Quickstart app has this behavior when the video icon is tapped:
![giphy](https://user-images.githubusercontent.com/21370530/57726835-ff5f9100-765d-11e9-9a8e-156fb77a90f6.gif)

The first time I press it, it unlocks the phone, but it doesn't bring the user to the app. Should this be handled in `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?)`?

Pressing the CallKit Quickstart button does bring you to the app.

This behavior occurs even when a real call is going on.

**Comment by piyushtank** [comment]
@timtraversy Thanks for reaching out. I was able to reproduce the problem. The app is not setting the `supportedHandleTypes` on the `providerConfiguration` which is causing the bug. 

I have opened a pull request to fix this bug in our sample app. https://github.com/twilio/video-quickstart-swift/pull/390 
Try it out and let me know if you have any questions.

Best,
Piyush

**Comment by timtraversy** [comment]
Thank you! I believe this can be closed.
