### ISSUE TITLE
TwilioVideo.framework does not support Bitcode

### ISSUE THREAD

**Issue by bcbroussard** [twilio/video-quickstart-swift#40]
The quickstart project builds fine, but adding the `TwilioVideo.framework` to a brand new app and then building for an ios device throws a linker error.

The error which appears is:

```
ld: '<path>/TwilioVideo/TwilioVideo.framework/TwilioVideo' does not 
contain bitcode. You must rebuild it with bitcode enabled (Xcode setting 
ENABLE_BITCODE), obtain an updated library from the vendor, or disable 
bitcode for this target. for architecture arm64
```

The error can be fixed by adding the build setting `ENABLE_BITCODE=NO`, but this disables iTunes app thinning.

Could the final frameworks support app thinning and bitcode re-optimizations? 
If not, it would be good to have this in the documentation.

[Apple Bitcode reference docs](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html)

**Comment by ceaglest** [comment]
@bcbroussard Thanks for writing in. We do not support Bitcode yet, but will be adding this during the beta process. I will update our [release notes](https://www.twilio.com/docs/api/video/changelogs/ios) to clarify that this feature is still in progress.

**Comment by bcbroussard** [comment]
@ceaglest that sounds great, thanks.

**Comment by sunny1076** [comment]
when u r planing ...to release version  which support Bitcode..

**Comment by ceaglest** [comment]
@sunny1076 At this point we are aiming to ship Bitcode support in Q1 of 2017.

Our 1st party, and most of our 3rd party dependencies support Bitcode - with the important exception of WebRTC. Since Bitcode is an all or nothing feature we've had to disable it in our SDK builds.

**Comment by sunny1076** [comment]
@ceaglest thanks for info.
@ceaglest i am getting a error  when am coming back from chat room to my ViewController its give me error and error log is this one..please go through that please suggest what am doing wrong

ERROR:TwilioVideo:[Platform]:Tried to copy a frame while stopped.
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

**Comment by ceaglest** [comment]
@sunny1076 Can you please open a separate issue for this?

It would be helpful if you could include logs, and a full stack trace. Sounds to me like an AVCaptureSession was interrupted, and was resurrected but is trying to deliver frames into some dead memory.

**Comment by jondwillis** [comment]
@ceaglest looks like [WebRTC bitcode is official](https://bugs.chromium.org/p/webrtc/issues/detail?id=5085)

`./tools-webrtc/ios/build_ios_libs.sh -e`

**Comment by ceaglest** [comment]
Hi @jondwillis,

We've been making internal WebRTC builds with Bitcode enabled based upon the 57 release branch. I will update this ticket once we ship an iOS beta release with this feature.

Thanks,
Chris

**Comment by ceaglest** [comment]
The latest `1.0.0-beta13` release adds support for Bitcode. We've also enabled Bitcode in our example apps.

https://www.twilio.com/docs/api/video/changelogs/ios#100-beta13-march-30-2017

**Comment by jondwillis** [comment]
I actually ended up disabling bitcode during development because WebRTC w/ Bitcode is absolutely huge and it slows down code-debug cycles noticeably on my machine.

**Comment by sunny1076** [comment]
Hi Christopher ,

Can you please tell me that how can i get to know " who is speaking now in
call ".

Thanks & Regards
Gaurav Mishra

**Comment by ceaglest** [comment]
Hi @sunny1076,

Can you open a separate issue for this?

Cheers,
Chris

**Comment by sunny1076** [comment]
Ok Chris,
