### ISSUE TITLE
The operation couldn’t be completed. (com.twilio.video error 2.) & (com.twilio.video error 0)

### ISSUE THREAD

**Issue by lmick002** [twilio/video-quickstart-swift#54]
Im using the PHP server SDK 5 and the tokens are recieved to my device but once I try to create/join a room It get this error. : "Failed to connect to room with error The operation couldn’t be completed. (com.twilio.video error 2.)"  . Then I tried to switch to PHP Server SDK 4 and I started to receive  (com.twilio.video error 0.). In both cases the token was successfully retrieved to the device.

**Comment by ceaglest** [comment]
Hi @lmick002,

It looks like something is amiss in your PHP token issuing server. I'm assuming you are using `1.0.0-beta3`of the iOS SDK based upon the error codes that you mentioned. If you are seeing `TVIErrorInvalidAccessToken` it means that the token didn't contain a valid account sid in the `sub` field. An unknown error probably indicates that something else was amiss with your configuration profile, or expiry time.

```
typedef NS_ENUM(NSUInteger, TVIError ) {
   TVIErrorUnknown = 0,
   TVIErrorSignaling,
   TVIErrorInvalidAccessToken,
};
```

Try using [jwt.io](jwt.io) to examine your token further. They should look something like:

```
{
  "jti": "SKxxxxxxx",
  "grants": {
    "video": {
      "configuration_profile_sid": "VSxxxxxxx"
    }
  },
  "iat": 1481786014,
  "exp": 1481789614,
  "iss": "SKxxxxxxx",
  "sub": "ACxxxxxxx"
}
```

**Comment by lmick002** [comment]
@ceaglest Thanks for your help it looks as though when I create it on the twilio dashboard it contains all the keys 
<img width="512" alt="doc1" src="https://cloud.githubusercontent.com/assets/11696955/21230972/ac413528-c2b4-11e6-932f-c96a42b1b431.png">

but when I use the php server its missing keys 

<img width="512" alt="doc2" src="https://cloud.githubusercontent.com/assets/11696955/21230991/bc00d306-c2b4-11e6-9036-afc7e013b403.png">

**Comment by ceaglest** [comment]
@lmick002 You might need to configure your PHP server to use your Account Sid. Are you using:

https://github.com/TwilioDevEd/video-quickstart-php

If so you need to edit the `config.php` to include this information.

**Comment by lmick002** [comment]
@ceaglest Ive resolved it. There was an error with the keys. Thanks!

**Comment by pranita88pawar** [comment]
@lmick002  Could you please let me know the steps you followed to resolve this issue, i am facing the same problem and stuck on it from last 4 -5 days.

![image](https://cloud.githubusercontent.com/assets/6493869/23611351/d6291428-029c-11e7-8400-69feb2328b53.png)

This token i got , but still throwing the same error.
Please help.Thanks !

**Comment by lmick002** [comment]
hey @pranita88pawar I found out that there was mismatch of the keys that show in the documentation.  So I had to make sure the `$twilioAccountSid,
    $twilioApiKey,
    $twilioApiSecret,` matched (Cap sensitive) or else it would return null
