### ISSUE TITLE
Cell phone running hot with a few minutes of video

### ISSUE THREAD

**Issue by top2tech** [twilio/video-quickstart-swift#60]
Cell phone running hot with a few minutes of video chat.
Repro both in iphone 6 plus and latest iphone 7 plus.

Does twilio video use GPU, or just software encoding/decoding?

Thanks

**Comment by ceaglest** [comment]
Hi @top2tech,

Thanks for writing in. At the moment our SDK only supports the VP8 video codec which uses software encoding and decoding. We plan to offer H.264 support in future releases, but at the moment this is listed as a known issue in our change log. Apple's iOS devices support H.264 via a hardware codec so this is going to be the best performing option in the long term, at least for small scale P2P streaming.

https://www.twilio.com/docs/api/video/changelogs/ios

We've also got some other improvements planned when it comes to performance, namely enforcing stricter bandwidth limits to reduce the encoding / decoding load.

Video rendering does use the GPU (we support both Metal and OpenGL ES), but at the moment an extra copy is made when frames are uploaded. In the near term (beta6 or 7) we will rectify this issue adding zero copy support for local video. This was enabled by some changes to the rendering APIs made in our last beta5 release.

We appreciate the feedback, and understand that performance is not where we want it to be in the SDK at the moment. We will start with the zero copy renderer changes I mentioned and follow up with H.264 support and bandwidth limits.

Thanks again,
Chris

**Comment by top2tech** [comment]
Thanks Chris for the detailed explanation.

Twilio Video is an awesome product, so easy and so affordable to have p2p video chat, this will enlighten a lot of scenarios. Thanks a lot for the great work!

Looking forward to performance and feature improvement...
