### ISSUE TITLE
TVITrack is not updating properly

### ISSUE THREAD

**Issue by chinna834** [twilio/video-quickstart-swift#64]
Using the video quick start with call kit  example as reference provided in the GitHub.

Adding multiple users into the video call conversation and ending the video call works fine. After doing the similar process for couple of times, i am not receiving the proper TVITrack from the delegate method where it shows a blank screen instead of remote view. Even my local video seems not updating properly to web server(vice-versa). 

At some point of time, while working on other views, i got the below error message.

**ERROR:TwilioVideo:[Platform]:Fatal runtime capture error: Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x17425adf0 {Error Domain=NSOSStatusErrorDomain Code=-12785 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-12785), NSLocalizedDescription=The operation could not be completed}, code -11800**

**Comment by ceaglest** [comment]
Hi @chinna834,

> Using the video quick start with call kit example as reference provided in the GitHub.
> 
> Adding multiple users into the video call conversation and ending the video call works fine. After doing the similar process for couple of times, i am not receiving the proper TVITrack from the delegate method where it shows a blank screen instead of remote view. Even my local video seems not updating properly to web server(vice-versa).
> 

How many participants are in the Room when you encounter this issue? If you are hard killing your app between testing runs you may be seeing an older Participant who has not been booted out of the Room yet. Please note that the CallKit example only renders video from a single remote Participant at a time.


> At some point of time, while working on other views, i got the below error message.
> 
> ERROR:TwilioVideo:[Platform]:Fatal runtime capture error: Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSUnderlyingError=0x17425adf0 {Error Domain=NSOSStatusErrorDomain Code=-12785 "(null)"}, NSLocalizedFailureReason=An unknown error occurred (-12785), NSLocalizedDescription=The operation could not be completed}, code -11800
> 

The code `AVErrorUnknown` looks pretty generic, can you explain more about the use case? In the CallKit example we only create a single TVICameraCapturer, and reuse it when joining / leaving a Room. Does your app create multiple TVICameraCapturer instances at the same time by any chance? If possible, it would be great to see some logs leading up to the capturer error.

Best,
Chris

**Comment by ceaglest** [comment]
Closing this ticket due to inactivity. @chinna834 please re-open if you can provide more information about your usage.
