### ISSUE TITLE
Enhanced Audio Support

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#66]
Currently, the Video SDK has no support for external audio equipment, such as bluetooth headphones, or plugging in an external microphone. This is required for my application, and I would really like to use the Twilio SDK. Is this something you could consider adding to TVIAudioTrack.

Perhaps there could be a class method with that shows the available devices, and then when one is created, you could pass in a matching identifier.

**Comment by ptankTwilio** [comment]
Hi @mknippen, Thanks for reaching out to us. 

You can set audio output by setting an appropriate modes on TVIAudioController. You can get TVIAudioController object from TVILocalMedia. 

Documentation: [TVIAudioController](https://media.twiliocdn.com/sdk/ios/video/releases/1.0.0-beta7/docs/Classes/TVIAudioController.html) and [TVIAudioOutput](https://media.twiliocdn.com/sdk/ios/video/releases/1.0.0-beta7/docs/Constants/TVIAudioOutput.html)

Let me know if you have any questions.

**Comment by mknippen** [comment]
@ptankTwilio as far as I can talk, this is only for audio output. I'm looking for something to attach a custom audio input. 

I'm currently testing with the Blue Raspberry Microphone (http://www.bluemic.com/products/raspberry/) and unable to get the audio from the microphone. This microphone works throughout iOS, such as the voice memo's app without any additional SDK.

**Comment by ptankTwilio** [comment]
@mknippen  Our Video SDK sets `AVAudioSessionCategoryPlayAndRecord`  category in `AVAudioSessionModeVideoChat` mode. If an external device does not support required audio routes for video chat movde, will not work with Video sdk.

Per description (http://www.bluemic.com/products/raspberry/), it looks like,  Blue Raspberry Microphone is not a supported device in `AVAudioSessionModeVideoChat` mode. The Microphone does not support required audio routes play and record (microphone supports supports record only it seems). So you may not be able to use the microphone with SDK. I am sorry about that.

Please note that external bluetooth headsets are supported audio routes and you should be able to use them.

**Comment by mknippen** [comment]
@ptankTwilio thank you for clarification. The Blue Raspberry is an audio in/out accessory, it has a headphone jack for audio out. Ideally, it would be really nice for me to be able to provide my own AVAudioRecorder object, or offer some further form of expansion like you do for video.

**Comment by ceaglest** [comment]
Closing this issue, we will be sharing more information about improved audio support shortly.
