### ISSUE TITLE
1.0.0-beta7 does not exist in cocoapod

### ISSUE THREAD

**Issue by top2tech** [twilio/video-quickstart-swift#68]
I'm using below in podfile:
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'
pod 'TwilioVideo', '1.0.0-beta7'

pod install failed with below message:

- `TwilioVideo (= 1.0.0-beta7)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `TwilioVideo (= 1.0.0-beta7)`.

**Comment by ceaglest** [comment]
@top2tech try `pod repo update twilio`, you probably just need to fetch the latest spec.

**Comment by top2tech** [comment]
Never mind. after run "pod repo update", beta7 was found and installed successfully.
