### ISSUE TITLE
Library not found for libPods-TwilioVideo-VideoQuickStart.a

### ISSUE THREAD

**Issue by jannunzi** [twilio/video-quickstart-swift#70]
I successfully updated twilio pod and installed it:

pod repo update twilio
pod install

but when I try to build from within XCode, I get the following missing library:

Library not found for -lPods-TwilioVideo-VideoQuickStart
Linker command failed with exit code 1 (use -v to see invocation)

Thanks, Jose

**Comment by ceaglest** [comment]
Hi @jannunzi,

Are you still running into this issue? It sounds like you tried to build from the Xcode project rather than the workspace after running `pod install`.

Best,
Chris

**Comment by ceaglest** [comment]
Hi @jannunzi,

Hopefully you were able to get up and running via Cocoapods. Please re-open if you are still having any issues with your dev setup.

Cheers,
Chris

**Comment by jayeshkv** [comment]
Hi @jannunzi 

I am facing the same issues, it builds fine and runs fine locally but when I try to archive it I get the same error, installed via pod file

this is my pod file

> source 'https://github.com/CocoaPods/Specs'
> 
> abstract_target 'TwilioVideo' do
>   pod 'TwilioVideo', '~> 3.2'
> 
> target 'projectname' do
>   platform :ios, '11.0'
>   project 'projectname.xcproject'
> end
> 
> end

ld: library not found for -lPods-TwilioVideo-projectname
clang: error: linker command failed with exit code 1 (use -v to see invocation)


I used the .xcworkspace file to open build & archive via xcode. Let me know if you need additional details.
