### ISSUE TITLE
TwilioVideo SDK Bitcode support

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#71]
When building my application, Bitcode is not enabled for this SDK. This makes it impossible to build an application with Bitcode, which has many benefits when sending to the App Store. It should be as simple as enabling it in Xcode Build Settings.

Error Message:
ld: 'TwilioVideo' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by idelgado** [comment]
@mknippen We are actively working to enable bitcode in our SDK. We are in the process of making all our dependencies compatible for bitcode and we expect to have support in the next few weeks. We'll update this ticket once we have support.

**Comment by mknippen** [comment]
Awesome, thanks!

**Comment by mknippen** [comment]
Closing as this is a duplicate of #40
