### ISSUE TITLE
Audio does not work on iOS simulators

### ISSUE THREAD

**Issue by mobihunterz** [twilio/video-quickstart-swift#73]
I have followed all steps mentioned in the quickstart example with generating access tokens for device and simulator separately and installed app at both sides. When I call from my device to simulator, video works. I can see my video on simulator but audio does not come. I tried it many times but no audio. I checked speakers and everything but no success.

Please let me know if there is any quick solution. At least quickstart example should work.

**Comment by ptankTwilio** [comment]
@mobihunterz  Audio playout and recording does not work correctly on simulators is a known issue in Video SDK - https://www.twilio.com/docs/api/video/changelogs/ios#100-beta8-february-17-2017

I will let you know when this is fixed. I am sorry for the inconvenience.

**Comment by ceaglest** [comment]
Hi @mobihunterz and others,

I am pleased to say that our [1.2.0](https://www.twilio.com/docs/api/video/changelogs/ios#120-july-6-2017) release adds support for playback and recording on the iOS simulator.

There are however, some minor limitations. Firstly, you should set the sample rate of your computer's audio device to 48 khz. We tested the built-in audio device only.

![screen shot 2017-07-06 at 6 21 12 pm](https://user-images.githubusercontent.com/1302577/27939171-ed20ee22-6277-11e7-875c-653d12ad8d92.png)
![screen shot 2017-07-06 at 9 54 54 am](https://user-images.githubusercontent.com/1302577/27939154-ca685e92-6277-11e7-96cc-3df12e15579a.png)

After selecting 48 kHz I/O we had success with the following iOS simulator / Xcode combinations.

**Xcode 9.0 Beta 2**

| Simulator | Operating System |
| ---------- | -------------|
| iPhone 7 Plus | iOS 11, iOS 10.2 |
| iPhone 7 | iOS 11, iOS 10.2 |
| iPhone 6s | iOS 11, iOS 10.2 |
| iPhone 6s | iOS 11, iOS 10.2, iOS 10.0 |
| iPhone 6 Plus | iOS 11, iOS 10.2 |
| iPhone 6 | iOS 11, iOS 10.2 |
| iPhone 5s | iOS 11, iOS 10.2 |
| iPhone 5 | iOS 10.2 |
| iPhone 4s | iOS 9.0 |

**Xcode 8.3.3**

| Simulator | Operating System |
| ---------- | -------------|
| iPhone 7 Plus | iOS 10.3, iOS 10.2 |
| iPhone 7 | iOS 10.3, iOS 10.2 |
| iPhone 6s | iOS 10.3, iOS 10.2 |
| iPhone 6s | iOS 10.3, iOS 10.2, iOS 10.0 |
| iPhone 6 Plus | iOS 10.3, iOS 10.2 |
| iPhone 6 | iOS 10.3, iOS 10.2 |
| iPhone 5s | iOS 10.3, iOS 10.2 |
| iPhone 5 | iOS 10.3 |
| iPhone 4s | iOS 9.0 |

Best,
Chris Eagleston

**Comment by ceaglest** [comment]
Closing this issue since it's been resolved in our last release. We still plan to migrate this info to our docs pages.

**Comment by mobihunterz** [comment]
Thanks for the info. I will check this.
