### ISSUE TITLE
Heap Corruption Crashes - Multiparty Rooms

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#74]
We performed tests with six users, and almost all of us had crashes with the current version (beta 8). Crashlytics noted at least 7 different crashes in the TwilioVideo codebase. I will be happy to provide stack traces for each one.
<img width="1219" alt="screen shot 2017-02-25 at 10 12 56 am" src="https://cloud.githubusercontent.com/assets/210156/23332680/4ce39a36-fb43-11e6-8d2f-cec9367b496a.png">

**Comment by mknippen** [comment]
Would you like each one as a separate GitHub issue, so it can be more easily tracked?

**Comment by idelgado** [comment]
@mknippen yes, that would be really helpful. Please add the stack trace for each and we'll start investigating.

**Comment by mknippen** [comment]
<img width="1209" alt="screen shot 2017-02-27 at 2 11 46 pm" src="https://cloud.githubusercontent.com/assets/210156/23377736/b70d082a-fcf6-11e6-9304-d529717275fa.png">

Attached finished demo results. We had 9 users, and 30 crashes. I will update with individual crash logs today.

**Comment by ceaglest** [comment]
Thanks for filing stack traces @mknippen.

We have customers using the iOS SDK in production who are not seeing the kind of crash rates that you are, so we may contact you for more info on your particular use case. Nevertheless, there are some memory and threading bugs that we are still working to resolve, and will keep you in the loop as we resolve these issues.

Best,
Chris

**Comment by mknippen** [comment]
@ceaglest absolutely, and sorry for the GitHub notification overload (I'm sure). I'm here to help in anyway that I can. I'm able to hop on a phone call or screenshare to show you what I'm doing at any point if you would like.

To the best of my knowledge, I'm not hacking anything or using anything outside of the SDK you published. I make no reference to AVFoundation or AudioToolbox at all, and let the framework handle it all directly.

**Comment by ceaglest** [comment]
@mknippen Other than https://github.com/twilio/video-quickstart-swift/issues/85 it looks the issues have the same underlying problem - heap corruption. Each crashing call is trying to allocate some memory, but the system libraries are detecting corruption and crashing from there.

**Comment by ceaglest** [comment]
Crash in consume_record.

Biggest crash on the demo. 8 crashes from 6 users in 30 minutes.

[TwilioVideo.consume_record.txt](https://github.com/twilio/video-quickstart-swift/files/811850/TwilioVideo.consume_record.txt)

**Comment by ceaglest** [comment]
Crash in `resip::ConnectionBase::preparseNewBytes` due to heap corruption.

[resip-ConnectionBase-preparse.txt](https://github.com/twilio/video-quickstart-swift/files/811855/resip-ConnectionBase-preparse.txt)

**Comment by ceaglest** [comment]
Crash in `cricket::P2PTransportChannel::IsPingable` likely due to heap corruption.

2 crashes from 2 users in 30 minutes

[cricket-P2PTransportChannel.crash.txt](https://github.com/twilio/video-quickstart-swift/files/811866/cricket-P2PTransportChannel.crash.txt)

**Comment by ceaglest** [comment]
Crash in `resip::Helper::makeResponse` due to heap corruption.

[resip-Helper.crash.txt](https://github.com/twilio/video-quickstart-swift/files/811867/resip-Helper.crash.txt)

**Comment by ceaglest** [comment]
Crash in `rtc::ByteBufferWriter::~ByteBufferWriter()` due to heap corruption.

[rtc-ByteBufferWriter-crash.txt](https://github.com/twilio/video-quickstart-swift/files/811868/rtc-ByteBufferWriter-crash.txt)

**Comment by ceaglest** [comment]
Crash in `sigslot::signal2<cricket::TransportChannel*, rtc::SentPacket const&, sigslot::single_threaded>` likely due to heap corruption.

[sigslot-signal2.crash.txt](https://github.com/twilio/video-quickstart-swift/files/811870/sigslot-signal2.crash.txt)

**Comment by ceaglest** [comment]
Crash in `resip::TransactionState::processSipMessageAsNew` due to heap corruption.

[resip-TransactionState.crash.txt](https://github.com/twilio/video-quickstart-swift/files/811871/resip-TransactionState.crash.txt)

**Comment by ceaglest** [comment]
Crash in `twilio::signaling::SipTU:process` due to heap corruption.

[twilio-signaling.crash.txt](https://github.com/twilio/video-quickstart-swift/files/811874/twilio-signaling.crash.txt)

**Comment by ceaglest** [comment]
@mknippen our latest 1.0.0-beta11 release should address the source of these heap corruption crashes. Give it a try if you have the chance.

**Comment by ceaglest** [comment]
Closing out this issue, since we haven't gotten any new reports of this type of crash since `1.0.0-beta11`. Please re-open if you are still experiencing issues.
