### ISSUE TITLE
cricket::P2PTransportChannel::IsPingable(cricket::Connection const*, long long) const crash

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#77]
2 crashes from 2 users in 30 minutes. One of the crashes referenced in #74.

[cricket-P2PTransportChannel crash.txt](https://github.com/twilio/video-quickstart-swift/files/805080/cricket-P2PTransportChannel.crash.txt)

**Comment by ceaglest** [comment]
Also looks like heap corruption, folded into #74.
