### ISSUE TITLE
twilio::signaling::RoomSignalingImpl crash

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#78]
2 crashes from 2 users in 30 minutes. One of the crashes referenced in #74.
[twilio-signaling crash.txt](https://github.com/twilio/video-quickstart-swift/files/805081/twilio-signaling.crash.txt)

**Comment by ceaglest** [comment]
Also separate from the heap corruption crashes. We are actively working on this threading bug and hope to squash it in `1.0.0-beta9`.

**Comment by ceaglest** [comment]
@mknippen We just released 1.0.0-beta11 which should resolve this crash. I'll leave this ticket open for a little while, please let us know if you are still experiencing this issue in your app.

**Comment by ceaglest** [comment]
Closing out this issue, since we haven't gotten any new reports of this type of crash since `1.0.0-beta11`. Please re-open if you are still experiencing issues.
