### ISSUE TITLE
twilio::signaling::PeerConnectionSignaling crash

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#85]
Occurs in `twilio::signaling::PeerConnectionSignaling::onSetSessionRemoteDescription(twilio::video::TwilioError)`

One of the crashes referenced in #74.

[twilio-signaling-peerconnection crash.txt](https://github.com/twilio/video-quickstart-swift/files/805112/twilio-signaling-peerconnection.crash.txt)

**Comment by ceaglest** [comment]
We are aware of this crash, and it should be resolved in the `1.0.0-beta9` release.

**Comment by ceaglest** [comment]
Partially resolved in `1.0.0-beta9` but still reproducible in some scenarios. Aiming for `1.0.0-beta10` to completely resolve this issue.

**Comment by ceaglest** [comment]
The behavior in `beta10` is the same as `beta9`, we are now targeting this fix for `1.0.0-beta11`.

**Comment by ceaglest** [comment]
@mknippen We just released `1.0.0-beta11` which should resolve the last instances of this crash. I'll leave this ticket open for a little while, please let us know if you are still experiencing this issue in your app.

**Comment by ceaglest** [comment]
Closing out this issue, since we haven't gotten any new reports of this type of crash since `1.0.0-beta11`. Please re-open if you are still experiencing issues.
