### ISSUE TITLE
Various AudioToolbox Crashes

### ISSUE THREAD

**Issue by mknippen** [twilio/video-quickstart-swift#86]
I received 4 different crashes that we're all in the AudioToolbox code. I know this isn't necessarily a bug in the Twilio code, but maybe there's something you can change so it's not crashing inside Apple's code. Either way, I just wanted to make you aware of it, as the only place that AudioToolbox is being used in our app is in the TwilioVideo SDK.

[AudioToolbox-crash.txt](https://github.com/twilio/video-quickstart-swift/files/805114/AudioToolbox-crash.txt)
[AudioToolbox-crash2.txt](https://github.com/twilio/video-quickstart-swift/files/805115/AudioToolbox-crash2.txt)
[AudioToolbox-crash3.txt](https://github.com/twilio/video-quickstart-swift/files/805117/AudioToolbox-crash3.txt)
[AudioToolbox-crash4.txt](https://github.com/twilio/video-quickstart-swift/files/805116/AudioToolbox-crash4.txt)

**Comment by ceaglest** [comment]
These may be heap corruption related, but for now I'm going to keep this ticket open separately.

A little more context, these crashes are occurring in multi-party Rooms where only audio is being shared.

**Comment by ceaglest** [comment]
Closing out this issue, since we haven't gotten any new reports of this type of crash since `1.0.0-beta11`. Please re-open if you are still experiencing issues.
