### ISSUE TITLE
Network handoff to/from a NAT'd IPv6 network

### ISSUE THREAD

**Issue by ceaglest** [twilio/video-quickstart-swift#87]
This is an enhancement we are making to our network handoff capabilities in preparation for our first General Availability release.

**Problem Description**

A Client `Alice` connects to a Room from a NAT'd IPv6 network. The connection succeeds and at a later time `Alice` switches to another network. The handoff to the new network fails, and eventually a `room:didDisconnect` callback is raised.

The same issue occurs when `Alice` connects over an IPv4 network, and then attempts to transition to a NAT'd IPv6 network. The NAT mapping needs to be re-established in order to open a connection on the new network.

**Comment by ceaglest** [comment]
We tried our best to deliver this fix in time for our `1.0.0` release. We are very close, but it looks like this enhancement will not land until `1.0.1`.

**Comment by paynerc** [comment]
`1.0.1` of Twilio Video has *just* been released which addresses this issue.
